void frameMissingProcess(void)
{
FRAME_MISSING_HANDLE(bcm_general_status, Bcm_general_status);
FRAME_MISSING_HANDLE(hum_time, Hum_time);
FRAME_MISSING_HANDLE(ac_control, Ac_control);
FRAME_MISSING_HANDLE(tpms_sys_status, Tpms_sys_status);
FRAME_MISSING_HANDLE(peps_general_status, Peps_general_status);
FRAME_MISSING_HANDLE(escl_general_status, Escl_general_status);
FRAME_MISSING_HANDLE(peps_general_status_2, Peps_general_status_2);
FRAME_MISSING_HANDLE(avm_general_status, Avm_general_status);
FRAME_MISSING_HANDLE(ems_engine_temp_and_barrometer, Ems_engine_temp_and_barrometer);
FRAME_MISSING_HANDLE(ahl_general_status, Ahl_general_status);
FRAME_MISSING_HANDLE(bcm_general_status_2, Bcm_general_status_2);
FRAME_MISSING_HANDLE(hum_event_command_1, Hum_event_command_1);
FRAME_MISSING_HANDLE(tcu_engine_torque_request, Tcu_engine_torque_request);
FRAME_MISSING_HANDLE(ems_engine_speed_and_torque, Ems_engine_speed_and_torque);
FRAME_MISSING_HANDLE(ems_general_status, Ems_general_status);
FRAME_MISSING_HANDLE(ems_start_stop, Ems_start_stop);
FRAME_MISSING_HANDLE(general_status_tcs_esp, General_status_tcs_esp);
FRAME_MISSING_HANDLE(ecs_immo_rand_number, Ecs_immo_rand_number);
FRAME_MISSING_HANDLE(icm_event_command, Icm_event_command);
FRAME_MISSING_HANDLE(eps_status, Eps_status);
FRAME_MISSING_HANDLE(sdm_general_status, Sdm_general_status);
FRAME_MISSING_HANDLE(ems_engine_fuel_and_turbo, Ems_engine_fuel_and_turbo);
FRAME_MISSING_HANDLE(ems_engine_idle_and_vspeed, Ems_engine_idle_and_vspeed);
FRAME_MISSING_HANDLE(tcu_general_status, Tcu_general_status);
}
