void frameMissingProcess(void)
{
FRAME_MISSING_HANDLE(ecs_immo_rand_number, Ecs_immo_rand_number, Ecs_immo_rand_numberMissingCounter);
FRAME_MISSING_HANDLE(tcu_engine_torque_request, Tcu_engine_torque_request, Tcu_engine_torque_requestMissingCounter);
FRAME_MISSING_HANDLE(ems_engine_speed_and_torque, Ems_engine_speed_and_torque, Ems_engine_speed_and_torqueMissingCounter);
FRAME_MISSING_HANDLE(ems_general_status, Ems_general_status, Ems_general_statusMissingCounter);
FRAME_MISSING_HANDLE(ems_start_stop, Ems_start_stop, Ems_start_stopMissingCounter);
FRAME_MISSING_HANDLE(general_status_tcs_esp, General_status_tcs_esp, General_status_tcs_espMissingCounter);
FRAME_MISSING_HANDLE(eps_status, Eps_status, Eps_statusMissingCounter);
FRAME_MISSING_HANDLE(sdm_general_status, Sdm_general_status, Sdm_general_statusMissingCounter);
FRAME_MISSING_HANDLE(ems_engine_fuel_and_turbo, Ems_engine_fuel_and_turbo, Ems_engine_fuel_and_turboMissingCounter);
FRAME_MISSING_HANDLE(ems_engine_idle_and_vspeed, Ems_engine_idle_and_vspeed, Ems_engine_idle_and_vspeedMissingCounter);
FRAME_MISSING_HANDLE(tcu_general_status, Tcu_general_status, Tcu_general_statusMissingCounter);
FRAME_MISSING_HANDLE(bcm_general_status, Bcm_general_status, Bcm_general_statusMissingCounter);
FRAME_MISSING_HANDLE(hum_time, Hum_time, Hum_timeMissingCounter);
FRAME_MISSING_HANDLE(ac_control, Ac_control, Ac_controlMissingCounter);
FRAME_MISSING_HANDLE(tpms_sys_status, Tpms_sys_status, Tpms_sys_statusMissingCounter);
FRAME_MISSING_HANDLE(peps_general_status, Peps_general_status, Peps_general_statusMissingCounter);
FRAME_MISSING_HANDLE(escl_general_status, Escl_general_status, Escl_general_statusMissingCounter);
FRAME_MISSING_HANDLE(peps_general_status_2, Peps_general_status_2, Peps_general_status_2MissingCounter);
FRAME_MISSING_HANDLE(avm_general_status, Avm_general_status, Avm_general_statusMissingCounter);
FRAME_MISSING_HANDLE(ems_engine_temp_and_barrometer, Ems_engine_temp_and_barrometer, Ems_engine_temp_and_barrometerMissingCounter);
FRAME_MISSING_HANDLE(ahl_general_status, Ahl_general_status, Ahl_general_statusMissingCounter);
FRAME_MISSING_HANDLE(bcm_general_status_2, Bcm_general_status_2, Bcm_general_status_2MissingCounter);
FRAME_MISSING_HANDLE(hum_event_command_1, Hum_event_command_1, Hum_event_command_1MissingCounter);
FRAME_MISSING_HANDLE(hum_event_command_2, Hum_event_command_2, Hum_event_command_2MissingCounter);
FRAME_MISSING_HANDLE(navi_information, Navi_information, Navi_informationMissingCounter);
FRAME_MISSING_HANDLE(media_information, Media_information, Media_informationMissingCounter);
}
