/************************************************************************
**
** Description:     RH850 D1M1H PORT_DIO_REG16_LIST generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-08-19 17:45:54
************************************************************************/
#define      PORT_DIO_REG16_LIST \
{ PORT0 ,    (uint16*)(&PORT_AWOP0) ,    (uint16*)(&PORT_AWOPPR0) }, \
{ PORT1 ,    (uint16*)(&PORT_ISOP1) ,    (uint16*)(&PORT_ISOPPR1) }, \
{ PORT3 ,    (uint16*)(&PORT_ISOP3) ,    (uint16*)(&PORT_ISOPPR3) }, \
{ PORT10 ,    (uint16*)(&PORT_ISOP10) ,    (uint16*)(&PORT_ISOPPR10) }, \
{ PORT11 ,    (uint16*)(&PORT_ISOP11) ,    (uint16*)(&PORT_ISOPPR11) }, \
{ PORT16 ,    (uint16*)(&PORT_ISOP16) ,    (uint16*)(&PORT_ISOPPR16) }, \
{ PORT17 ,    (uint16*)(&PORT_ISOP17) ,    (uint16*)(&PORT_ISOPPR17) }, \
{ PORT21 ,    (uint16*)(&PORT_ISOP21) ,    (uint16*)(&PORT_ISOPPR21) }, \
{ PORT42 ,    (uint16*)(&PORT_ISOP42) ,    (uint16*)(&PORT_ISOPPR42) }, \
{ PORT43 ,    (uint16*)(&PORT_ISOP43) ,    (uint16*)(&PORT_ISOPPR43) }, \
{ PORT44 ,    (uint16*)(&PORT_ISOP44) ,    (uint16*)(&PORT_ISOPPR44) }, \
{ PORT45 ,    (uint16*)(&PORT_ISOP45) ,    (uint16*)(&PORT_ISOPPR45) }, \
{ JPORT0 ,    (uint16*)(&PORTJ_AWOJP0) ,    (uint16*)(&PORTJ_AWOJPPR0) }, \
/***************************************************************************
**
** Description:     RH850 D1M1H PIN_DIO_REG16_LIST generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-08-19 17:45:54
***************************************************************************/
#define      PIN_DIO_REG16_LIST     \
{ PORT0_0, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_0)   }, \
{ PORT0_1, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_1)   }, \
{ PORT0_2, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_2)   }, \
{ PORT0_3, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_3)   }, \
{ PORT0_4, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_4)   }, \
{ PORT0_5, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_5)   }, \
{ PORT0_6, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_6)   }, \
{ PORT0_7, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_7)   }, \
{ PORT0_8, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_8)   }, \
{ PORT0_9, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_9)   }, \
{ PORT1_0, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_0)   }, \
{ PORT1_1, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_1)   }, \
{ PORT1_2, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_2)   }, \
{ PORT1_3, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_3)   }, \
{ PORT1_4, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_4)   }, \
{ PORT1_5, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_5)   }, \
{ PORT3_0, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_0)   }, \
{ PORT3_1, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_1)   }, \
{ PORT3_2, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_2)   }, \
{ PORT3_3, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_3)   }, \
{ PORT3_4, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_4)   }, \
{ PORT3_5, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_5)   }, \
{ PORT3_6, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_6)   }, \
{ PORT3_7, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_7)   }, \
{ PORT3_8, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_8)   }, \
{ PORT3_9, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_9)   }, \
{ PORT10_0, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_0)   }, \
{ PORT10_1, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_1)   }, \
{ PORT10_2, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_2)   }, \
{ PORT10_3, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_3)   }, \
{ PORT10_4, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_4)   }, \
{ PORT10_5, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_5)   }, \
{ PORT10_6, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_6)   }, \
{ PORT10_7, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_7)   }, \
{ PORT10_8, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_8)   }, \
{ PORT10_9, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_9)   }, \
{ PORT10_10, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_10)   }, \
{ PORT10_11, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_11)   }, \
{ PORT11_0, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_0)   }, \
{ PORT11_1, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_1)   }, \
{ PORT11_2, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_2)   }, \
{ PORT11_3, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_3)   }, \
{ PORT16_0, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_0)   }, \
{ PORT16_1, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_1)   }, \
{ PORT16_2, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_2)   }, \
{ PORT16_3, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_3)   }, \
{ PORT16_4, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_4)   }, \
{ PORT16_5, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_5)   }, \
{ PORT16_6, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_6)   }, \
{ PORT16_7, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_7)   }, \
{ PORT16_8, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_8)   }, \
{ PORT16_9, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_9)   }, \
{ PORT16_10, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_10)   }, \
{ PORT16_11, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_11)   }, \
{ PORT17_0, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_0)   }, \
{ PORT17_1, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_1)   }, \
{ PORT17_2, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_2)   }, \
{ PORT17_3, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_3)   }, \
{ PORT17_4, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_4)   }, \
{ PORT17_5, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_5)   }, \
{ PORT17_6, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_6)   }, \
{ PORT17_7, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_7)   }, \
{ PORT17_8, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_8)   }, \
{ PORT17_9, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_9)   }, \
{ PORT17_10, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_10)   }, \
{ PORT17_11, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_11)   }, \
{ PORT21_0, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_0)   }, \
{ PORT21_1, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_1)   }, \
{ PORT21_2, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_2)   }, \
{ PORT21_3, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_3)   }, \
{ PORT21_4, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_4)   }, \
{ PORT21_5, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_5)   }, \
{ PORT21_6, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_6)   }, \
{ PORT21_7, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_7)   }, \
{ PORT21_8, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_8)   }, \
{ PORT21_9, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_9)   }, \
{ PORT42_0, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_0)   }, \
{ PORT42_1, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_1)   }, \
{ PORT42_2, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_2)   }, \
{ PORT42_3, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_3)   }, \
{ PORT42_4, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_4)   }, \
{ PORT42_5, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_5)   }, \
{ PORT42_6, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_6)   }, \
{ PORT42_7, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_7)   }, \
{ PORT42_8, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_8)   }, \
{ PORT42_9, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_9)   }, \
{ PORT42_10, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_10)   }, \
{ PORT42_11, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_11)   }, \
{ PORT42_12, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_12)   }, \
{ PORT42_13, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_13)   }, \
{ PORT42_14, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_14)   }, \
{ PORT42_15, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_15)   }, \
{ PORT43_0, (uint16 *) &PORT_ISOP43 , (uint16 *) &PORT_ISOPPR43,  (uint16)(BIT_0)   }, \
{ PORT43_1, (uint16 *) &PORT_ISOP43 , (uint16 *) &PORT_ISOPPR43,  (uint16)(BIT_1)   }, \
{ PORT44_0, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_0)   }, \
{ PORT44_1, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_1)   }, \
{ PORT44_2, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_2)   }, \
{ PORT44_3, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_3)   }, \
{ PORT44_4, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_4)   }, \
{ PORT44_5, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_5)   }, \
{ PORT44_6, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_6)   }, \
{ PORT44_7, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_7)   }, \
{ PORT44_8, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_8)   }, \
{ PORT44_9, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_9)   }, \
{ PORT44_10, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_10)   }, \
{ PORT44_11, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_11)   }, \
{ PORT45_0, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_0)   }, \
{ PORT45_1, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_1)   }, \
{ PORT45_2, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_2)   }, \
{ PORT45_3, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_3)   }, \
{ PORT45_4, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_4)   }, \
{ PORT45_5, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_5)   }, \
{ PORT45_6, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_6)   }, \
{ PORT45_7, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_7)   }, \
{ PORT45_8, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_8)   }, \
{ PORT45_9, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_9)   }, \
{ PORT45_10, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_10)   }, \
{ PORT45_11, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_11)   }, \
{ PORT45_12, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_12)   }, \
{ PORT45_13, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_13)   }, \
{ JPORT0_0, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_0)   }, \
{ JPORT0_1, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_1)   }, \
{ JPORT0_2, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_2)   }, \
{ JPORT0_3, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_3)   }, \
{ JPORT0_4, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_4)   }, \
