/******************************************************************************
**  (c) copyright 2016
**  Company       O-film
**                All rights reserved
**  Secrecy Level STRICTLY CONFIDENTIAL
*******************************************************************************
**
**          File  : Dio_Cfg.h
**          Description: RH850D1M1H digital IO configuration file, generated by tool automatically.
**                           Don't modify it manually.
**          Author:  jiangyuchang
**          Porting: niujianlong
**
**          Date  : 2016-07-29 19:58:12
**
**
******************************************************************************/
#ifndef DIO_CFG_H
#define DIO_CFG_H

/******************************************************************************
**    INCLUDES
******************************************************************************/
#include "board.h"
#include "device.h"


/******************************************************************************
**    MACROS
******************************************************************************/

/***********PORT 0 GROUP PORT BIT OPERATION***********/
#define      IGN_INT_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_0)
#define      IGN_INT_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_0)
#define      IGN_INT_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_0)
#define      FLMD1_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_1)
#define      FLMD1_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_1)
#define      FLMD1_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_1)
#define      HW_O_M_CAN_STB_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_2)
#define      HW_O_M_CAN_STB_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_2)
#define      HW_O_M_CAN_STB_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_2)
#define      HW_O_M_CAN_EN_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_3)
#define      HW_O_M_CAN_EN_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_3)
#define      HW_O_M_CAN_EN_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_3)
#define      M_CAN_TX_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_4)
#define      M_CAN_TX_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_4)
#define      M_CAN_TX_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_4)
#define      M_CAN_RX_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_5)
#define      M_CAN_RX_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_5)
#define      M_CAN_RX_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_5)
#define      V_CAN_TX_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_6)
#define      V_CAN_TX_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_6)
#define      V_CAN_TX_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_6)
#define      V_CAN_RX_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_7)
#define      V_CAN_RX_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_7)
#define      V_CAN_RX_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_7)
#define      M_CAN_ERR_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_8)
#define      M_CAN_ERR_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_8)
#define      M_CAN_ERR_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_8)
#define      TELLTALE_SPI_CS_BSET_PORT()                                       SETBIT(PORT_AWOP0, BIT_9)
#define      TELLTALE_SPI_CS_BCLR_PORT()                                       CLEARBIT(PORT_AWOP0, BIT_9)
#define      TELLTALE_SPI_CS_BTEST_PORT()                                       TESTBIT(PORT_AWOPPR0, BIT_9)

/***********PORT 1 GROUP PORT BIT OPERATION***********/
#define      LED_SPI_DATA_BSET_PORT()                                       SETBIT(PORT_ISOP1, BIT_0)
#define      LED_SPI_DATA_BCLR_PORT()                                       CLEARBIT(PORT_ISOP1, BIT_0)
#define      LED_SPI_DATA_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR1, BIT_0)
#define      LED_SPI_LATCH_BSET_PORT()                                       SETBIT(PORT_ISOP1, BIT_1)
#define      LED_SPI_LATCH_BCLR_PORT()                                       CLEARBIT(PORT_ISOP1, BIT_1)
#define      LED_SPI_LATCH_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR1, BIT_1)
#define      LED_SPI_CLK_BSET_PORT()                                       SETBIT(PORT_ISOP1, BIT_2)
#define      LED_SPI_CLK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP1, BIT_2)
#define      LED_SPI_CLK_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR1, BIT_2)
#define      TELLTALE_SPI_DATA_BSET_PORT()                                       SETBIT(PORT_ISOP1, BIT_3)
#define      TELLTALE_SPI_DATA_BCLR_PORT()                                       CLEARBIT(PORT_ISOP1, BIT_3)
#define      TELLTALE_SPI_DATA_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR1, BIT_3)
#define      TELLTALE_SPI_LATCH_BSET_PORT()                                       SETBIT(PORT_ISOP1, BIT_4)
#define      TELLTALE_SPI_LATCH_BCLR_PORT()                                       CLEARBIT(PORT_ISOP1, BIT_4)
#define      TELLTALE_SPI_LATCH_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR1, BIT_4)
#define      TELLTALE_SPI_CLK_BSET_PORT()                                       SETBIT(PORT_ISOP1, BIT_5)
#define      TELLTALE_SPI_CLK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP1, BIT_5)
#define      TELLTALE_SPI_CLK_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR1, BIT_5)

/***********PORT 3 GROUP PORT BIT OPERATION***********/
#define      VIDEO_SDA_MDIO_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_0)
#define      VIDEO_SDA_MDIO_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_0)
#define      VIDEO_SDA_MDIO_BTEST_PORT()                                       TESTBIT(PPR3, BIT_0)
#define      VIDEO_SCL_MDC_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_1)
#define      VIDEO_SCL_MDC_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_1)
#define      VIDEO_SCL_MDC_BTEST_PORT()                                       TESTBIT(PPR3, BIT_1)
#define      ETNB_INT_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_2)
#define      ETNB_INT_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_2)
#define      ETNB_INT_BTEST_PORT()                                       TESTBIT(PPR3, BIT_2)
#define      SPEAKER_I2S_TXD_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_3)
#define      SPEAKER_I2S_TXD_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_3)
#define      SPEAKER_I2S_TXD_BTEST_PORT()                                       TESTBIT(PPR3, BIT_3)
#define      SPEAKER_I2S_BIT_CLK_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_4)
#define      SPEAKER_I2S_BIT_CLK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_4)
#define      SPEAKER_I2S_BIT_CLK_BTEST_PORT()                                       TESTBIT(PPR3, BIT_4)
#define      SPEAKER_I2S_WS_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_5)
#define      SPEAKER_I2S_WS_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_5)
#define      SPEAKER_I2S_WS_BTEST_PORT()                                       TESTBIT(PPR3, BIT_5)
#define      SPEAKER_SYSCLK_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_6)
#define      SPEAKER_SYSCLK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_6)
#define      SPEAKER_SYSCLK_BTEST_PORT()                                       TESTBIT(PPR3, BIT_6)
#define      CODEC_MUTE_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_7)
#define      CODEC_MUTE_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_7)
#define      CODEC_MUTE_BTEST_PORT()                                       TESTBIT(PPR3, BIT_7)
#define      SPEAKER_OUTPUT_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_8)
#define      SPEAKER_OUTPUT_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_8)
#define      SPEAKER_OUTPUT_BTEST_PORT()                                       TESTBIT(PPR3, BIT_8)
#define      SS_CTRL_BSET_PORT()                                       SETBIT(PORT_ISOP3, BIT_9)
#define      SS_CTRL_BCLR_PORT()                                       CLEARBIT(PORT_ISOP3, BIT_9)
#define      SS_CTRL_BTEST_PORT()                                       TESTBIT(PPR3, BIT_9)

/***********PORT 10 GROUP PORT BIT OPERATION***********/
#define      TFT_THERMAL_MON_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_0)
#define      TFT_THERMAL_MON_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_0)
#define      TFT_THERMAL_MON_BTEST_PORT()                                       TESTBIT(PPR10, BIT_0)
#define      BAT_MON_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_1)
#define      BAT_MON_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_1)
#define      BAT_MON_BTEST_PORT()                                       TESTBIT(PPR10, BIT_1)
#define      SBATT_MON_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_2)
#define      SBATT_MON_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_2)
#define      SBATT_MON_BTEST_PORT()                                       TESTBIT(PPR10, BIT_2)
#define      SW5V_MON_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_3)
#define      SW5V_MON_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_3)
#define      SW5V_MON_BTEST_PORT()                                       TESTBIT(PPR10, BIT_3)
#define      FUEL_IN_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_4)
#define      FUEL_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_4)
#define      FUEL_IN_BTEST_PORT()                                       TESTBIT(PPR10, BIT_4)
#define      SW5V_REF_IN_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_5)
#define      SW5V_REF_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_5)
#define      SW5V_REF_IN_BTEST_PORT()                                       TESTBIT(PPR10, BIT_5)
#define      STEERING_IN_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_6)
#define      STEERING_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_6)
#define      STEERING_IN_BTEST_PORT()                                       TESTBIT(PPR10, BIT_6)
#define      BACKLIGHT_IN_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_7)
#define      BACKLIGHT_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_7)
#define      BACKLIGHT_IN_BTEST_PORT()                                       TESTBIT(PPR10, BIT_7)
#define      AIRBAG_FB_IN_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_8)
#define      AIRBAG_FB_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_8)
#define      AIRBAG_FB_IN_BTEST_PORT()                                       TESTBIT(PPR10, BIT_8)
#define      NO_USED_PIN_109_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_9)
#define      NO_USED_PIN_109_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_9)
#define      NO_USED_PIN_109_BTEST_PORT()                                       TESTBIT(PPR10, BIT_9)
#define      SW5V_EN_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_10)
#define      SW5V_EN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_10)
#define      SW5V_EN_BTEST_PORT()                                       TESTBIT(PPR10, BIT_10)
#define      V_CAN_STB_BSET_PORT()                                       SETBIT(PORT_ISOP10, BIT_11)
#define      V_CAN_STB_BCLR_PORT()                                       CLEARBIT(PORT_ISOP10, BIT_11)
#define      V_CAN_STB_BTEST_PORT()                                       TESTBIT(PPR10, BIT_11)

/***********PORT 11 GROUP PORT BIT OPERATION***********/
#define      RADA_CLK_IN_BSET_PORT()                                       SETBIT(PORT_ISOP11, BIT_0)
#define      RADA_CLK_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP11, BIT_0)
#define      RADA_CLK_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR11, BIT_0)
#define      RADA_DATA_IN_BSET_PORT()                                       SETBIT(PORT_ISOP11, BIT_1)
#define      RADA_DATA_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP11, BIT_1)
#define      RADA_DATA_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR11, BIT_1)
#define      SBATT_EN_BSET_PORT()                                       SETBIT(PORT_ISOP11, BIT_2)
#define      SBATT_EN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP11, BIT_2)
#define      SBATT_EN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR11, BIT_2)
#define      LEFT_TT_TT3_BSET_PORT()                                       SETBIT(PORT_ISOP11, BIT_3)
#define      LEFT_TT_TT3_BCLR_PORT()                                       CLEARBIT(PORT_ISOP11, BIT_3)
#define      LEFT_TT_TT3_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR11, BIT_3)

/***********PORT 16 GROUP PORT BIT OPERATION***********/
#define      SPEEDO_1P_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_0)
#define      SPEEDO_1P_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_0)
#define      SPEEDO_1P_BTEST_PORT()                                       TESTBIT(PPR16, BIT_0)
#define      SPEEDO_1N_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_1)
#define      SPEEDO_1N_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_1)
#define      SPEEDO_1N_BTEST_PORT()                                       TESTBIT(PPR16, BIT_1)
#define      SPEEDO_2P_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_2)
#define      SPEEDO_2P_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_2)
#define      SPEEDO_2P_BTEST_PORT()                                       TESTBIT(PPR16, BIT_2)
#define      SPEEDO_2N_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_3)
#define      SPEEDO_2N_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_3)
#define      SPEEDO_2N_BTEST_PORT()                                       TESTBIT(PPR16, BIT_3)
#define      TEMP_1P_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_4)
#define      TEMP_1P_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_4)
#define      TEMP_1P_BTEST_PORT()                                       TESTBIT(PPR16, BIT_4)
#define      TEMP_1N_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_5)
#define      TEMP_1N_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_5)
#define      TEMP_1N_BTEST_PORT()                                       TESTBIT(PPR16, BIT_5)
#define      TEMP_2P_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_6)
#define      TEMP_2P_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_6)
#define      TEMP_2P_BTEST_PORT()                                       TESTBIT(PPR16, BIT_6)
#define      TEMP_2N_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_7)
#define      TEMP_2N_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_7)
#define      TEMP_2N_BTEST_PORT()                                       TESTBIT(PPR16, BIT_7)
#define      FUEL_1P_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_8)
#define      FUEL_1P_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_8)
#define      FUEL_1P_BTEST_PORT()                                       TESTBIT(PPR16, BIT_8)
#define      FUEL_1N_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_9)
#define      FUEL_1N_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_9)
#define      FUEL_1N_BTEST_PORT()                                       TESTBIT(PPR16, BIT_9)
#define      FUEL_2P_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_10)
#define      FUEL_2P_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_10)
#define      FUEL_2P_BTEST_PORT()                                       TESTBIT(PPR16, BIT_10)
#define      FUEL_2N_BSET_PORT()                                       SETBIT(PORT_ISOP16, BIT_11)
#define      FUEL_2N_BCLR_PORT()                                       CLEARBIT(PORT_ISOP16, BIT_11)
#define      FUEL_2N_BTEST_PORT()                                       TESTBIT(PPR16, BIT_11)

/***********PORT 17 GROUP PORT BIT OPERATION***********/
#define      CHARGE_IN_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_0)
#define      CHARGE_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_0)
#define      CHARGE_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_0)
#define      P3V3_SW_EN_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_1)
#define      P3V3_SW_EN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_1)
#define      P3V3_SW_EN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_1)
#define      LEFT_GAUGE_PWM_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_2)
#define      LEFT_GAUGE_PWM_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_2)
#define      LEFT_GAUGE_PWM_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_2)
#define      LEFT_POINTER_PWM_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_3)
#define      LEFT_POINTER_PWM_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_3)
#define      LEFT_POINTER_PWM_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_3)
#define      RIGHT_POINTER_PWM_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_4)
#define      RIGHT_POINTER_PWM_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_4)
#define      RIGHT_POINTER_PWM_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_4)
#define      RIGHT_GAUGE_PWM_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_5)
#define      RIGHT_GAUGE_PWM_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_5)
#define      RIGHT_GAUGE_PWM_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_5)
#define      TT_PWM_CTRL_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_6)
#define      TT_PWM_CTRL_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_6)
#define      TT_PWM_CTRL_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_6)
#define      PARK_BRAKE_IN_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_7)
#define      PARK_BRAKE_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_7)
#define      PARK_BRAKE_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_7)
#define      TFT_BL_PWM_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_8)
#define      TFT_BL_PWM_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_8)
#define      TFT_BL_PWM_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_8)
#define      NIGHT_PANEL_CTRL_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_9)
#define      NIGHT_PANEL_CTRL_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_9)
#define      NIGHT_PANEL_CTRL_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_9)
#define      WASH_FLUID_IN_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_10)
#define      WASH_FLUID_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_10)
#define      WASH_FLUID_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_10)
#define      BRAKE_FLUID_IN_BSET_PORT()                                       SETBIT(PORT_ISOP17, BIT_11)
#define      BRAKE_FLUID_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP17, BIT_11)
#define      BRAKE_FLUID_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR17, BIT_11)

/***********PORT 21 GROUP PORT BIT OPERATION***********/
#define      QSPI_SCK_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_0)
#define      QSPI_SCK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_0)
#define      QSPI_SCK_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_0)
#define      QSPI_CS_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_1)
#define      QSPI_CS_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_1)
#define      QSPI_CS_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_1)
#define      QSPI_IO0_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_2)
#define      QSPI_IO0_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_2)
#define      QSPI_IO0_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_2)
#define      QSPI_IO1_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_3)
#define      QSPI_IO1_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_3)
#define      QSPI_IO1_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_3)
#define      QSPI_IO2_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_4)
#define      QSPI_IO2_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_4)
#define      QSPI_IO2_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_4)
#define      QSPI_IO3_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_5)
#define      QSPI_IO3_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_5)
#define      QSPI_IO3_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_5)
#define      ETNB_RST_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_6)
#define      ETNB_RST_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_6)
#define      ETNB_RST_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_6)
#define      ETNB_EN_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_7)
#define      ETNB_EN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_7)
#define      ETNB_EN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_7)
#define      LOW_OIL_PRESSURE_IN_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_8)
#define      LOW_OIL_PRESSURE_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_8)
#define      LOW_OIL_PRESSURE_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_8)
#define      NIGHT_PANNEL_IN_BSET_PORT()                                       SETBIT(PORT_ISOP21, BIT_9)
#define      NIGHT_PANNEL_IN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP21, BIT_9)
#define      NIGHT_PANNEL_IN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR21, BIT_9)

/***********PORT 42 GROUP PORT BIT OPERATION***********/
#define      ETNB_TXD3_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_0)
#define      ETNB_TXD3_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_0)
#define      ETNB_TXD3_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_0)
#define      ETNB_TXD2_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_1)
#define      ETNB_TXD2_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_1)
#define      ETNB_TXD2_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_1)
#define      ETNB_TXD1_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_2)
#define      ETNB_TXD1_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_2)
#define      ETNB_TXD1_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_2)
#define      ETNB_TXD0_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_3)
#define      ETNB_TXD0_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_3)
#define      ETNB_TXD0_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_3)
#define      ETNB_TXEN_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_4)
#define      ETNB_TXEN_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_4)
#define      ETNB_TXEN_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_4)
#define      ETNB_TXER_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_5)
#define      ETNB_TXER_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_5)
#define      ETNB_TXER_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_5)
#define      NO_USED_PIN426_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_6)
#define      NO_USED_PIN426_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_6)
#define      NO_USED_PIN426_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_6)
#define      NO_USED_PIN427_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_7)
#define      NO_USED_PIN427_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_7)
#define      NO_USED_PIN427_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_7)
#define      ETNB_TXCLK_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_8)
#define      ETNB_TXCLK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_8)
#define      ETNB_TXCLK_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_8)
#define      ETNB_RXCLK_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_9)
#define      ETNB_RXCLK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_9)
#define      ETNB_RXCLK_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_9)
#define      ETNB_RXD3_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_10)
#define      ETNB_RXD3_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_10)
#define      ETNB_RXD3_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_10)
#define      ETNB_RXD2_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_11)
#define      ETNB_RXD2_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_11)
#define      ETNB_RXD2_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_11)
#define      ETNB_RXD1_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_12)
#define      ETNB_RXD1_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_12)
#define      ETNB_RXD1_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_12)
#define      ETNB_RXD0_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_13)
#define      ETNB_RXD0_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_13)
#define      ETNB_RXD0_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_13)
#define      ETNB_RXDV_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_14)
#define      ETNB_RXDV_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_14)
#define      ETNB_RXDV_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_14)
#define      ETNB_RXER_BSET_PORT()                                       SETBIT(PORT_ISOP42, BIT_15)
#define      ETNB_RXER_BCLR_PORT()                                       CLEARBIT(PORT_ISOP42, BIT_15)
#define      ETNB_RXER_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR42, BIT_15)

/***********PORT 43 GROUP PORT BIT OPERATION***********/
#define      TFT_RESET_BSET_PORT()                                       SETBIT(PORT_ISOP43, BIT_0)
#define      TFT_RESET_BCLR_PORT()                                       CLEARBIT(PORT_ISOP43, BIT_0)
#define      TFT_RESET_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR43, BIT_0)
#define      TFT_STBYB_BSET_PORT()                                       SETBIT(PORT_ISOP43, BIT_1)
#define      TFT_STBYB_BCLR_PORT()                                       CLEARBIT(PORT_ISOP43, BIT_1)
#define      TFT_STBYB_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR43, BIT_1)

/***********PORT 44 GROUP PORT BIT OPERATION***********/
#define      TFT_RED7_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_0)
#define      TFT_RED7_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_0)
#define      TFT_RED7_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_0)
#define      TFT_RED6_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_1)
#define      TFT_RED6_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_1)
#define      TFT_RED6_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_1)
#define      TFT_RED5_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_2)
#define      TFT_RED5_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_2)
#define      TFT_RED5_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_2)
#define      TFT_RED4_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_3)
#define      TFT_RED4_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_3)
#define      TFT_RED4_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_3)
#define      TFT_RED3_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_4)
#define      TFT_RED3_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_4)
#define      TFT_RED3_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_4)
#define      TFT_RED2_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_5)
#define      TFT_RED2_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_5)
#define      TFT_RED2_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_5)
#define      TFT_RED1_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_6)
#define      TFT_RED1_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_6)
#define      TFT_RED1_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_6)
#define      TFT_RED0_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_7)
#define      TFT_RED0_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_7)
#define      TFT_RED0_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_7)
#define      TFT_GREEN7_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_8)
#define      TFT_GREEN7_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_8)
#define      TFT_GREEN7_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_8)
#define      TFT_GREEN6_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_9)
#define      TFT_GREEN6_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_9)
#define      TFT_GREEN6_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_9)
#define      TFT_GREEN5_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_10)
#define      TFT_GREEN5_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_10)
#define      TFT_GREEN5_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_10)
#define      TFT_GREEN4_BSET_PORT()                                       SETBIT(PORT_ISOP44, BIT_11)
#define      TFT_GREEN4_BCLR_PORT()                                       CLEARBIT(PORT_ISOP44, BIT_11)
#define      TFT_GREEN4_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR44, BIT_11)

/***********PORT 45 GROUP PORT BIT OPERATION***********/
#define      TFT_CLK_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_0)
#define      TFT_CLK_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_0)
#define      TFT_CLK_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_0)
#define      TFT_DE_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_1)
#define      TFT_DE_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_1)
#define      TFT_DE_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_1)
#define      TFT_GREEN3_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_2)
#define      TFT_GREEN3_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_2)
#define      TFT_GREEN3_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_2)
#define      TFT_GREEN2_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_3)
#define      TFT_GREEN2_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_3)
#define      TFT_GREEN2_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_3)
#define      TFT_GREEN1_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_4)
#define      TFT_GREEN1_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_4)
#define      TFT_GREEN1_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_4)
#define      TFT_GREEN0_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_5)
#define      TFT_GREEN0_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_5)
#define      TFT_GREEN0_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_5)
#define      TFT_BLUE7_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_6)
#define      TFT_BLUE7_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_6)
#define      TFT_BLUE7_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_6)
#define      TFT_BLUE6_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_7)
#define      TFT_BLUE6_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_7)
#define      TFT_BLUE6_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_7)
#define      TFT_BLUE5_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_8)
#define      TFT_BLUE5_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_8)
#define      TFT_BLUE5_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_8)
#define      TFT_BLUE4_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_9)
#define      TFT_BLUE4_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_9)
#define      TFT_BLUE4_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_9)
#define      TFT_BLUE3_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_10)
#define      TFT_BLUE3_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_10)
#define      TFT_BLUE3_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_10)
#define      TFT_BLUE2_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_11)
#define      TFT_BLUE2_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_11)
#define      TFT_BLUE2_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_11)
#define      TFT_BLUE1_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_12)
#define      TFT_BLUE1_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_12)
#define      TFT_BLUE1_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_12)
#define      TFT_BLUE0_BSET_PORT()                                       SETBIT(PORT_ISOP45, BIT_13)
#define      TFT_BLUE0_BCLR_PORT()                                       CLEARBIT(PORT_ISOP45, BIT_13)
#define      TFT_BLUE0_BTEST_PORT()                                       TESTBIT(PORT_ISOPPR45, BIT_13)

/***********JPORT 0 GROUP PORT BIT OPERATION***********/
#define      TDI_BSET_PORT()                                       SETBIT(PORTJ_AWOJP0, BIT_0)
#define      TDI_BCLR_PORT()                                       CLEARBIT(PORTJ_AWOJP0, BIT_0)
#define      TDI_BTEST_PORT()                                       TESTBIT(PORTJ_AWOJPPR0, BIT_0)
#define      TDO_BSET_PORT()                                       SETBIT(PORTJ_AWOJP0, BIT_1)
#define      TDO_BCLR_PORT()                                       CLEARBIT(PORTJ_AWOJP0, BIT_1)
#define      TDO_BTEST_PORT()                                       TESTBIT(PORTJ_AWOJPPR0, BIT_1)
#define      TCK_BSET_PORT()                                       SETBIT(PORTJ_AWOJP0, BIT_2)
#define      TCK_BCLR_PORT()                                       CLEARBIT(PORTJ_AWOJP0, BIT_2)
#define      TCK_BTEST_PORT()                                       TESTBIT(PORTJ_AWOJPPR0, BIT_2)
#define      TMS_BSET_PORT()                                       SETBIT(PORTJ_AWOJP0, BIT_3)
#define      TMS_BCLR_PORT()                                       CLEARBIT(PORTJ_AWOJP0, BIT_3)
#define      TMS_BTEST_PORT()                                       TESTBIT(PORTJ_AWOJPPR0, BIT_3)
#define      TRST_BSET_PORT()                                       SETBIT(PORTJ_AWOJP0, BIT_4)
#define      TRST_BCLR_PORT()                                       CLEARBIT(PORTJ_AWOJP0, BIT_4)
#define      TRST_BTEST_PORT()                                       TESTBIT(PORTJ_AWOJPPR0, BIT_4)


/*************DIO DBNC CONFIGURATION**************/
#define DIO_00_SET_TO_INPUT()              CLEARBIT(PORT_AWOPMC0,BIT_0);SETBIT(PORT_AWOPM0,BIT_0);SETBIT(PORT_AWOPIBC0,BIT_0)
#define DIO_00_BTEST_PORT()              TESTBIT(PORT_AWOPPR0, BIT_0)
#define IGN_INT_DBNC_CHANNEL              DIO_00_DBNC_CHANNEL
#define IGN_INT_BTEST_DBNC_PORT()              Dio_getDbncState(IGN_INT_DBNC_CHANNEL)
#define DIO_01_SET_TO_INPUT()              CLEARBIT(PORT_ISOPMC17,BIT_0);SETBIT(PORT_ISOPMC17,BIT_0);SETBIT(PORT_ISOPIBC17,BIT_0)
#define DIO_01_BTEST_PORT()              TESTBIT(PORT_ISOPPR17, BIT_0)
#define CHARGE_IN_DBNC_CHANNEL              DIO_01_DBNC_CHANNEL
#define CHARGE_IN_BTEST_DBNC_PORT()              Dio_getDbncState(CHARGE_IN_DBNC_CHANNEL)
#define DIO_02_SET_TO_INPUT()              CLEARBIT(PORT_ISOPMC21,BIT_9);SETBIT(PORT_ISOPMC21,BIT_9);SETBIT(PORT_ISOPIBC21,BIT_9)
#define DIO_02_BTEST_PORT()              TESTBIT(PORT_ISOPPR21, BIT_9)
#define NIGHT_PANNEL_IN_DBNC_CHANNEL              DIO_02_DBNC_CHANNEL
#define NIGHT_PANNEL_IN_BTEST_DBNC_PORT()              Dio_getDbncState(NIGHT_PANNEL_IN_DBNC_CHANNEL)

#define DIO_DBNC_INIT_COUNTER_BIT0    (0)
#define DIO_DBNC_INIT_COUNTER_BIT1    (4)
#define DIO_DBNC_INIT_COUNTER_BIT2    (4)
#define DIO_DBNC_INIT_COUNTER_BIT3    (3)

/*************END OF DIO DBNC CONFIGURATION**************/


/************************************************************************
**
** Description:     RH850 D1M1H PORT_DIO_REG16_LIST generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-29 19:58:12
************************************************************************/
#define      PORT_DIO_REG16_LIST \
{ PORT0 ,    (uint16*)(&PORT_AWOP0) ,    (uint16*)(&PORT_AWOPPR0) }, \
{ PORT1 ,    (uint16*)(&PORT_ISOP1) ,    (uint16*)(&PORT_ISOPPR1) }, \
{ PORT3 ,    (uint16*)(&PORT_ISOP3) ,    (uint16*)(&PORT_ISOPPR3) }, \
{ PORT10 ,    (uint16*)(&PORT_ISOP10) ,    (uint16*)(&PORT_ISOPPR10) }, \
{ PORT11 ,    (uint16*)(&PORT_ISOP11) ,    (uint16*)(&PORT_ISOPPR11) }, \
{ PORT16 ,    (uint16*)(&PORT_ISOP16) ,    (uint16*)(&PORT_ISOPPR16) }, \
{ PORT17 ,    (uint16*)(&PORT_ISOP17) ,    (uint16*)(&PORT_ISOPPR17) }, \
{ PORT21 ,    (uint16*)(&PORT_ISOP21) ,    (uint16*)(&PORT_ISOPPR21) }, \
{ PORT42 ,    (uint16*)(&PORT_ISOP42) ,    (uint16*)(&PORT_ISOPPR42) }, \
{ PORT43 ,    (uint16*)(&PORT_ISOP43) ,    (uint16*)(&PORT_ISOPPR43) }, \
{ PORT44 ,    (uint16*)(&PORT_ISOP44) ,    (uint16*)(&PORT_ISOPPR44) }, \
{ PORT45 ,    (uint16*)(&PORT_ISOP45) ,    (uint16*)(&PORT_ISOPPR45) }, \
{ JPORT0 ,    (uint16*)(&PORTJ_AWOJP0) ,    (uint16*)(&PORTJ_AWOJPPR0) }, \
/***************************************************************************
**
** Description:     RH850 D1M1H PIN_DIO_REG16_LIST generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-29 19:58:12
***************************************************************************/
#define      PIN_DIO_REG16_LIST     \
{ PORT0_0, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_0)   }, \
{ PORT0_1, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_1)   }, \
{ PORT0_2, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_2)   }, \
{ PORT0_3, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_3)   }, \
{ PORT0_4, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_4)   }, \
{ PORT0_5, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_5)   }, \
{ PORT0_6, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_6)   }, \
{ PORT0_7, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_7)   }, \
{ PORT0_8, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_8)   }, \
{ PORT0_9, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_9)   }, \
{ PORT1_0, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_0)   }, \
{ PORT1_1, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_1)   }, \
{ PORT1_2, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_2)   }, \
{ PORT1_3, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_3)   }, \
{ PORT1_4, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_4)   }, \
{ PORT1_5, (uint16 *) &PORT_ISOP1 , (uint16 *) &PORT_ISOPPR1,  (uint16)(BIT_5)   }, \
{ PORT3_0, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_0)   }, \
{ PORT3_1, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_1)   }, \
{ PORT3_2, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_2)   }, \
{ PORT3_3, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_3)   }, \
{ PORT3_4, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_4)   }, \
{ PORT3_5, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_5)   }, \
{ PORT3_6, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_6)   }, \
{ PORT3_7, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_7)   }, \
{ PORT3_8, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_8)   }, \
{ PORT3_9, (uint16 *) &PORT_ISOP3 , (uint16 *) &PORT_ISOPPR3,  (uint16)(BIT_9)   }, \
{ PORT10_0, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_0)   }, \
{ PORT10_1, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_1)   }, \
{ PORT10_2, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_2)   }, \
{ PORT10_3, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_3)   }, \
{ PORT10_4, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_4)   }, \
{ PORT10_5, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_5)   }, \
{ PORT10_6, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_6)   }, \
{ PORT10_7, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_7)   }, \
{ PORT10_8, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_8)   }, \
{ PORT10_9, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_9)   }, \
{ PORT10_10, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_10)   }, \
{ PORT10_11, (uint16 *) &PORT_ISOP10 , (uint16 *) &PORT_ISOPPR10,  (uint16)(BIT_11)   }, \
{ PORT11_0, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_0)   }, \
{ PORT11_1, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_1)   }, \
{ PORT11_2, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_2)   }, \
{ PORT11_3, (uint16 *) &PORT_ISOP11 , (uint16 *) &PORT_ISOPPR11,  (uint16)(BIT_3)   }, \
{ PORT16_0, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_0)   }, \
{ PORT16_1, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_1)   }, \
{ PORT16_2, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_2)   }, \
{ PORT16_3, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_3)   }, \
{ PORT16_4, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_4)   }, \
{ PORT16_5, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_5)   }, \
{ PORT16_6, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_6)   }, \
{ PORT16_7, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_7)   }, \
{ PORT16_8, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_8)   }, \
{ PORT16_9, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_9)   }, \
{ PORT16_10, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_10)   }, \
{ PORT16_11, (uint16 *) &PORT_ISOP16 , (uint16 *) &PORT_ISOPPR16,  (uint16)(BIT_11)   }, \
{ PORT17_0, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_0)   }, \
{ PORT17_1, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_1)   }, \
{ PORT17_2, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_2)   }, \
{ PORT17_3, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_3)   }, \
{ PORT17_4, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_4)   }, \
{ PORT17_5, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_5)   }, \
{ PORT17_6, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_6)   }, \
{ PORT17_7, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_7)   }, \
{ PORT17_8, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_8)   }, \
{ PORT17_9, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_9)   }, \
{ PORT17_10, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_10)   }, \
{ PORT17_11, (uint16 *) &PORT_ISOP17 , (uint16 *) &PORT_ISOPPR17,  (uint16)(BIT_11)   }, \
{ PORT21_0, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_0)   }, \
{ PORT21_1, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_1)   }, \
{ PORT21_2, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_2)   }, \
{ PORT21_3, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_3)   }, \
{ PORT21_4, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_4)   }, \
{ PORT21_5, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_5)   }, \
{ PORT21_6, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_6)   }, \
{ PORT21_7, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_7)   }, \
{ PORT21_8, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_8)   }, \
{ PORT21_9, (uint16 *) &PORT_ISOP21 , (uint16 *) &PORT_ISOPPR21,  (uint16)(BIT_9)   }, \
{ PORT42_0, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_0)   }, \
{ PORT42_1, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_1)   }, \
{ PORT42_2, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_2)   }, \
{ PORT42_3, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_3)   }, \
{ PORT42_4, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_4)   }, \
{ PORT42_5, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_5)   }, \
{ PORT42_6, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_6)   }, \
{ PORT42_7, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_7)   }, \
{ PORT42_8, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_8)   }, \
{ PORT42_9, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_9)   }, \
{ PORT42_10, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_10)   }, \
{ PORT42_11, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_11)   }, \
{ PORT42_12, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_12)   }, \
{ PORT42_13, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_13)   }, \
{ PORT42_14, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_14)   }, \
{ PORT42_15, (uint16 *) &PORT_ISOP42 , (uint16 *) &PORT_ISOPPR42,  (uint16)(BIT_15)   }, \
{ PORT43_0, (uint16 *) &PORT_ISOP43 , (uint16 *) &PORT_ISOPPR43,  (uint16)(BIT_0)   }, \
{ PORT43_1, (uint16 *) &PORT_ISOP43 , (uint16 *) &PORT_ISOPPR43,  (uint16)(BIT_1)   }, \
{ PORT44_0, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_0)   }, \
{ PORT44_1, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_1)   }, \
{ PORT44_2, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_2)   }, \
{ PORT44_3, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_3)   }, \
{ PORT44_4, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_4)   }, \
{ PORT44_5, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_5)   }, \
{ PORT44_6, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_6)   }, \
{ PORT44_7, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_7)   }, \
{ PORT44_8, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_8)   }, \
{ PORT44_9, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_9)   }, \
{ PORT44_10, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_10)   }, \
{ PORT44_11, (uint16 *) &PORT_ISOP44 , (uint16 *) &PORT_ISOPPR44,  (uint16)(BIT_11)   }, \
{ PORT45_0, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_0)   }, \
{ PORT45_1, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_1)   }, \
{ PORT45_2, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_2)   }, \
{ PORT45_3, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_3)   }, \
{ PORT45_4, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_4)   }, \
{ PORT45_5, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_5)   }, \
{ PORT45_6, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_6)   }, \
{ PORT45_7, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_7)   }, \
{ PORT45_8, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_8)   }, \
{ PORT45_9, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_9)   }, \
{ PORT45_10, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_10)   }, \
{ PORT45_11, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_11)   }, \
{ PORT45_12, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_12)   }, \
{ PORT45_13, (uint16 *) &PORT_ISOP45 , (uint16 *) &PORT_ISOPPR45,  (uint16)(BIT_13)   }, \
{ JPORT0_0, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_0)   }, \
{ JPORT0_1, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_1)   }, \
{ JPORT0_2, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_2)   }, \
{ JPORT0_3, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_3)   }, \
{ JPORT0_4, (uint16 *) &PORT_AWOP0 , (uint16 *) &PORT_AWOPPR0,  (uint16)(BIT_4)   }, \


#endif

/**************************************End Of File******************************************/
