/************************************************************************
**
** Description:     RH850 D1M1H Port Init Register List generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-14 19:26:51
************************************************************************/
#define      PORT_INIT_REG16_LIST \
{ (uint16 *) &PORT_AWOPMC0 ,    (uint16)(PORT_AWOPMC0_INIT) }, \
{ (uint16 *) &PORT_AWOPM0 ,    (uint16)(PORT_AWOPM0_INIT) }, \
{ (uint16 *) &PORT_AWOPIPC0 ,    (uint16)(PORT_AWOPIPC0_INIT) }, \
{ (uint16 *) &PORT_AWOPFCE0 ,    (uint16)(PORT_AWOPFCE0_INIT) }, \
{ (uint16 *) &PORT_AWOPFC0 ,    (uint16)(PORT_AWOPFC0_INIT) }, \
{ (uint16 *) &PORT_AWOPIBC0 ,    (uint16)(PORT_AWOPIBC0_INIT) }, \
{ (uint16 *) &PORT_AWOPBDC0 ,    (uint16)(PORT_AWOPBDC0_INIT) }, \
{ (uint16 *) &PORT_AWOP0 ,    (uint16)(PORT_AWOP0_INIT) }, \
{ (uint16 *) &PORT_AWOPU0 ,    (uint16)(PORT_AWOPU0_INIT) }, \
{ (uint16 *) &PORT_AWOPD0 ,    (uint16)(PORT_AWOPD0_INIT) }, \
{ (uint16 *) &PORT_AWOPODC0 ,    (uint16)(PORT_AWOPODC0_INIT) }, \
{ (uint16 *) &PORT_AWOPDSC0 ,    (uint16)(PORT_AWOPDSC0_INIT) }, \
{ (uint16 *) &PORT_ISOPMC1 ,    (uint16)(PORT_ISOPMC1_INIT) }, \
{ (uint16 *) &PORT_ISOPM1 ,    (uint16)(PORT_ISOPM1_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC1 ,    (uint16)(PORT_ISOPIPC1_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE1 ,    (uint16)(PORT_ISOPFCE1_INIT) }, \
{ (uint16 *) &PORT_ISOPFC1 ,    (uint16)(PORT_ISOPFC1_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC1 ,    (uint16)(PORT_ISOPIBC1_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC1 ,    (uint16)(PORT_ISOPBDC1_INIT) }, \
{ (uint16 *) &PORT_ISOP1 ,    (uint16)(PORT_ISOP1_INIT) }, \
{ (uint16 *) &PORT_ISOPU1 ,    (uint16)(PORT_ISOPU1_INIT) }, \
{ (uint16 *) &PORT_ISOPD1 ,    (uint16)(PORT_ISOPD1_INIT) }, \
{ (uint16 *) &PORT_ISOPODC1 ,    (uint16)(PORT_ISOPODC1_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC1 ,    (uint16)(PORT_ISOPDSC1_INIT) }, \
{ (uint16 *) &PORT_ISOPMC3 ,    (uint16)(PORT_ISOPMC3_INIT) }, \
{ (uint16 *) &PORT_ISOPM3 ,    (uint16)(PORT_ISOPM3_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC3 ,    (uint16)(PORT_ISOPIPC3_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE3 ,    (uint16)(PORT_ISOPFCE3_INIT) }, \
{ (uint16 *) &PORT_ISOPFC3 ,    (uint16)(PORT_ISOPFC3_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC3 ,    (uint16)(PORT_ISOPIBC3_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC3 ,    (uint16)(PORT_ISOPBDC3_INIT) }, \
{ (uint16 *) &PORT_ISOP3 ,    (uint16)(PORT_ISOP3_INIT) }, \
{ (uint16 *) &PORT_ISOPU3 ,    (uint16)(PORT_ISOPU3_INIT) }, \
{ (uint16 *) &PORT_ISOPD3 ,    (uint16)(PORT_ISOPD3_INIT) }, \
{ (uint16 *) &PORT_ISOPODC3 ,    (uint16)(PORT_ISOPODC3_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC3 ,    (uint16)(PORT_ISOPDSC3_INIT) }, \
{ (uint16 *) &PORT_ISOPMC10 ,    (uint16)(PORT_ISOPMC10_INIT) }, \
{ (uint16 *) &PORT_ISOPM10 ,    (uint16)(PORT_ISOPM10_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC10 ,    (uint16)(PORT_ISOPIPC10_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE10 ,    (uint16)(PORT_ISOPFCE10_INIT) }, \
{ (uint16 *) &PORT_ISOPFC10 ,    (uint16)(PORT_ISOPFC10_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC10 ,    (uint16)(PORT_ISOPIBC10_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC10 ,    (uint16)(PORT_ISOPBDC10_INIT) }, \
{ (uint16 *) &PORT_ISOP10 ,    (uint16)(PORT_ISOP10_INIT) }, \
{ (uint16 *) &PORT_ISOPU10 ,    (uint16)(PORT_ISOPU10_INIT) }, \
{ (uint16 *) &PORT_ISOPD10 ,    (uint16)(PORT_ISOPD10_INIT) }, \
{ (uint16 *) &PORT_ISOPODC10 ,    (uint16)(PORT_ISOPODC10_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC10 ,    (uint16)(PORT_ISOPDSC10_INIT) }, \
{ (uint16 *) &PORT_ISOPMC11 ,    (uint16)(PORT_ISOPMC11_INIT) }, \
{ (uint16 *) &PORT_ISOPM11 ,    (uint16)(PORT_ISOPM11_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC11 ,    (uint16)(PORT_ISOPIPC11_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE11 ,    (uint16)(PORT_ISOPFCE11_INIT) }, \
{ (uint16 *) &PORT_ISOPFC11 ,    (uint16)(PORT_ISOPFC11_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC11 ,    (uint16)(PORT_ISOPIBC11_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC11 ,    (uint16)(PORT_ISOPBDC11_INIT) }, \
{ (uint16 *) &PORT_ISOP11 ,    (uint16)(PORT_ISOP11_INIT) }, \
{ (uint16 *) &PORT_ISOPU11 ,    (uint16)(PORT_ISOPU11_INIT) }, \
{ (uint16 *) &PORT_ISOPD11 ,    (uint16)(PORT_ISOPD11_INIT) }, \
{ (uint16 *) &PORT_ISOPODC11 ,    (uint16)(PORT_ISOPODC11_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC11 ,    (uint16)(PORT_ISOPDSC11_INIT) }, \
{ (uint16 *) &PORT_ISOPMC16 ,    (uint16)(PORT_ISOPMC16_INIT) }, \
{ (uint16 *) &PORT_ISOPM16 ,    (uint16)(PORT_ISOPM16_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC16 ,    (uint16)(PORT_ISOPIPC16_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE16 ,    (uint16)(PORT_ISOPFCE16_INIT) }, \
{ (uint16 *) &PORT_ISOPFC16 ,    (uint16)(PORT_ISOPFC16_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC16 ,    (uint16)(PORT_ISOPIBC16_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC16 ,    (uint16)(PORT_ISOPBDC16_INIT) }, \
{ (uint16 *) &PORT_ISOP16 ,    (uint16)(PORT_ISOP16_INIT) }, \
{ (uint16 *) &PORT_ISOPU16 ,    (uint16)(PORT_ISOPU16_INIT) }, \
{ (uint16 *) &PORT_ISOPD16 ,    (uint16)(PORT_ISOPD16_INIT) }, \
{ (uint16 *) &PORT_ISOPODC16 ,    (uint16)(PORT_ISOPODC16_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC16 ,    (uint16)(PORT_ISOPDSC16_INIT) }, \
{ (uint16 *) &PORT_ISOPMC17 ,    (uint16)(PORT_ISOPMC17_INIT) }, \
{ (uint16 *) &PORT_ISOPM17 ,    (uint16)(PORT_ISOPM17_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC17 ,    (uint16)(PORT_ISOPIPC17_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE17 ,    (uint16)(PORT_ISOPFCE17_INIT) }, \
{ (uint16 *) &PORT_ISOPFC17 ,    (uint16)(PORT_ISOPFC17_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC17 ,    (uint16)(PORT_ISOPIBC17_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC17 ,    (uint16)(PORT_ISOPBDC17_INIT) }, \
{ (uint16 *) &PORT_ISOP17 ,    (uint16)(PORT_ISOP17_INIT) }, \
{ (uint16 *) &PORT_ISOPU17 ,    (uint16)(PORT_ISOPU17_INIT) }, \
{ (uint16 *) &PORT_ISOPD17 ,    (uint16)(PORT_ISOPD17_INIT) }, \
{ (uint16 *) &PORT_ISOPODC17 ,    (uint16)(PORT_ISOPODC17_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC17 ,    (uint16)(PORT_ISOPDSC17_INIT) }, \
{ (uint16 *) &PORT_ISOPMC21 ,    (uint16)(PORT_ISOPMC21_INIT) }, \
{ (uint16 *) &PORT_ISOPM21 ,    (uint16)(PORT_ISOPM21_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC21 ,    (uint16)(PORT_ISOPIPC21_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE21 ,    (uint16)(PORT_ISOPFCE21_INIT) }, \
{ (uint16 *) &PORT_ISOPFC21 ,    (uint16)(PORT_ISOPFC21_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC21 ,    (uint16)(PORT_ISOPIBC21_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC21 ,    (uint16)(PORT_ISOPBDC21_INIT) }, \
{ (uint16 *) &PORT_ISOP21 ,    (uint16)(PORT_ISOP21_INIT) }, \
{ (uint16 *) &PORT_ISOPU21 ,    (uint16)(PORT_ISOPU21_INIT) }, \
{ (uint16 *) &PORT_ISOPD21 ,    (uint16)(PORT_ISOPD21_INIT) }, \
{ (uint16 *) &PORT_ISOPODC21 ,    (uint16)(PORT_ISOPODC21_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC21 ,    (uint16)(PORT_ISOPDSC21_INIT) }, \
{ (uint16 *) &PORT_ISOPMC42 ,    (uint16)(PORT_ISOPMC42_INIT) }, \
{ (uint16 *) &PORT_ISOPM42 ,    (uint16)(PORT_ISOPM42_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC42 ,    (uint16)(PORT_ISOPIPC42_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE42 ,    (uint16)(PORT_ISOPFCE42_INIT) }, \
{ (uint16 *) &PORT_ISOPFC42 ,    (uint16)(PORT_ISOPFC42_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC42 ,    (uint16)(PORT_ISOPIBC42_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC42 ,    (uint16)(PORT_ISOPBDC42_INIT) }, \
{ (uint16 *) &PORT_ISOP42 ,    (uint16)(PORT_ISOP42_INIT) }, \
{ (uint16 *) &PORT_ISOPU42 ,    (uint16)(PORT_ISOPU42_INIT) }, \
{ (uint16 *) &PORT_ISOPD42 ,    (uint16)(PORT_ISOPD42_INIT) }, \
{ (uint16 *) &PORT_ISOPODC42 ,    (uint16)(PORT_ISOPODC42_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC42 ,    (uint16)(PORT_ISOPDSC42_INIT) }, \
{ (uint16 *) &PORT_ISOPMC43 ,    (uint16)(PORT_ISOPMC43_INIT) }, \
{ (uint16 *) &PORT_ISOPM43 ,    (uint16)(PORT_ISOPM43_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC43 ,    (uint16)(PORT_ISOPIPC43_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE43 ,    (uint16)(PORT_ISOPFCE43_INIT) }, \
{ (uint16 *) &PORT_ISOPFC43 ,    (uint16)(PORT_ISOPFC43_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC43 ,    (uint16)(PORT_ISOPIBC43_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC43 ,    (uint16)(PORT_ISOPBDC43_INIT) }, \
{ (uint16 *) &PORT_ISOP43 ,    (uint16)(PORT_ISOP43_INIT) }, \
{ (uint16 *) &PORT_ISOPU43 ,    (uint16)(PORT_ISOPU43_INIT) }, \
{ (uint16 *) &PORT_ISOPD43 ,    (uint16)(PORT_ISOPD43_INIT) }, \
{ (uint16 *) &PORT_ISOPODC43 ,    (uint16)(PORT_ISOPODC43_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC43 ,    (uint16)(PORT_ISOPDSC43_INIT) }, \
{ (uint16 *) &PORT_ISOPMC44 ,    (uint16)(PORT_ISOPMC44_INIT) }, \
{ (uint16 *) &PORT_ISOPM44 ,    (uint16)(PORT_ISOPM44_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC44 ,    (uint16)(PORT_ISOPIPC44_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE44 ,    (uint16)(PORT_ISOPFCE44_INIT) }, \
{ (uint16 *) &PORT_ISOPFC44 ,    (uint16)(PORT_ISOPFC44_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC44 ,    (uint16)(PORT_ISOPIBC44_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC44 ,    (uint16)(PORT_ISOPBDC44_INIT) }, \
{ (uint16 *) &PORT_ISOP44 ,    (uint16)(PORT_ISOP44_INIT) }, \
{ (uint16 *) &PORT_ISOPU44 ,    (uint16)(PORT_ISOPU44_INIT) }, \
{ (uint16 *) &PORT_ISOPD44 ,    (uint16)(PORT_ISOPD44_INIT) }, \
{ (uint16 *) &PORT_ISOPODC44 ,    (uint16)(PORT_ISOPODC44_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC44 ,    (uint16)(PORT_ISOPDSC44_INIT) }, \
{ (uint16 *) &PORT_ISOPMC45 ,    (uint16)(PORT_ISOPMC45_INIT) }, \
{ (uint16 *) &PORT_ISOPM45 ,    (uint16)(PORT_ISOPM45_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC45 ,    (uint16)(PORT_ISOPIPC45_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE45 ,    (uint16)(PORT_ISOPFCE45_INIT) }, \
{ (uint16 *) &PORT_ISOPFC45 ,    (uint16)(PORT_ISOPFC45_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC45 ,    (uint16)(PORT_ISOPIBC45_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC45 ,    (uint16)(PORT_ISOPBDC45_INIT) }, \
{ (uint16 *) &PORT_ISOP45 ,    (uint16)(PORT_ISOP45_INIT) }, \
{ (uint16 *) &PORT_ISOPU45 ,    (uint16)(PORT_ISOPU45_INIT) }, \
{ (uint16 *) &PORT_ISOPD45 ,    (uint16)(PORT_ISOPD45_INIT) }, \
{ (uint16 *) &PORT_ISOPODC45 ,    (uint16)(PORT_ISOPODC45_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC45 ,    (uint16)(PORT_ISOPDSC45_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPMC0 ,    (uint16)(PORTJ_AWOJPMC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPM0 ,    (uint16)(PORTJ_AWOJPM0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPIPC0 ,    (uint16)(PORTJ_AWOJPIPC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPFCE0 ,    (uint16)(PORTJ_AWOJPFCE0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPFC0 ,    (uint16)(PORTJ_AWOJPFC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPIBC0 ,    (uint16)(PORTJ_AWOJPIBC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPBDC0 ,    (uint16)(PORTJ_AWOJPBDC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJP0 ,    (uint16)(PORTJ_AWOJP0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPU0 ,    (uint16)(PORTJ_AWOJPU0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPD0 ,    (uint16)(PORTJ_AWOJPD0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPODC0 ,    (uint16)(PORTJ_AWOJPODC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPDSC0 ,    (uint16)(PORTJ_AWOJPDSC0_INIT) }, \
/************************************************************************
**
** Description:     RH850 D1M1H Port Sleep Register List generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-14 19:26:51
************************************************************************/
#define      PORT_SLEEP_REG16_LIST \
{ (uint16 *) &PORT_AWOPMC0 ,    (uint16)(PORT_AWOPMC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPM0 ,    (uint16)(PORT_AWOPM0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPIPC0 ,    (uint16)(PORT_AWOPIPC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPFCE0 ,    (uint16)(PORT_AWOPFCE0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPFC0 ,    (uint16)(PORT_AWOPFC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPIBC0 ,    (uint16)(PORT_AWOPIBC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPBDC0 ,    (uint16)(PORT_AWOPBDC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOP0 ,    (uint16)(PORT_AWOP0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPU0 ,    (uint16)(PORT_AWOPU0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPD0 ,    (uint16)(PORT_AWOPD0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPODC0 ,    (uint16)(PORT_AWOPODC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPDSC0 ,    (uint16)(PORT_AWOPDSC0_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC1 ,    (uint16)(PORT_ISOPMC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM1 ,    (uint16)(PORT_ISOPM1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC1 ,    (uint16)(PORT_ISOPIPC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE1 ,    (uint16)(PORT_ISOPFCE1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC1 ,    (uint16)(PORT_ISOPFC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC1 ,    (uint16)(PORT_ISOPIBC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC1 ,    (uint16)(PORT_ISOPBDC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOP1 ,    (uint16)(PORT_ISOP1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU1 ,    (uint16)(PORT_ISOPU1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD1 ,    (uint16)(PORT_ISOPD1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC1 ,    (uint16)(PORT_ISOPODC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC1 ,    (uint16)(PORT_ISOPDSC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC3 ,    (uint16)(PORT_ISOPMC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM3 ,    (uint16)(PORT_ISOPM3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC3 ,    (uint16)(PORT_ISOPIPC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE3 ,    (uint16)(PORT_ISOPFCE3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC3 ,    (uint16)(PORT_ISOPFC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC3 ,    (uint16)(PORT_ISOPIBC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC3 ,    (uint16)(PORT_ISOPBDC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOP3 ,    (uint16)(PORT_ISOP3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU3 ,    (uint16)(PORT_ISOPU3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD3 ,    (uint16)(PORT_ISOPD3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC3 ,    (uint16)(PORT_ISOPODC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC3 ,    (uint16)(PORT_ISOPDSC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC10 ,    (uint16)(PORT_ISOPMC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM10 ,    (uint16)(PORT_ISOPM10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC10 ,    (uint16)(PORT_ISOPIPC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE10 ,    (uint16)(PORT_ISOPFCE10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC10 ,    (uint16)(PORT_ISOPFC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC10 ,    (uint16)(PORT_ISOPIBC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC10 ,    (uint16)(PORT_ISOPBDC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOP10 ,    (uint16)(PORT_ISOP10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU10 ,    (uint16)(PORT_ISOPU10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD10 ,    (uint16)(PORT_ISOPD10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC10 ,    (uint16)(PORT_ISOPODC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC10 ,    (uint16)(PORT_ISOPDSC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC11 ,    (uint16)(PORT_ISOPMC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM11 ,    (uint16)(PORT_ISOPM11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC11 ,    (uint16)(PORT_ISOPIPC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE11 ,    (uint16)(PORT_ISOPFCE11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC11 ,    (uint16)(PORT_ISOPFC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC11 ,    (uint16)(PORT_ISOPIBC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC11 ,    (uint16)(PORT_ISOPBDC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOP11 ,    (uint16)(PORT_ISOP11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU11 ,    (uint16)(PORT_ISOPU11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD11 ,    (uint16)(PORT_ISOPD11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC11 ,    (uint16)(PORT_ISOPODC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC11 ,    (uint16)(PORT_ISOPDSC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC16 ,    (uint16)(PORT_ISOPMC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM16 ,    (uint16)(PORT_ISOPM16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC16 ,    (uint16)(PORT_ISOPIPC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE16 ,    (uint16)(PORT_ISOPFCE16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC16 ,    (uint16)(PORT_ISOPFC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC16 ,    (uint16)(PORT_ISOPIBC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC16 ,    (uint16)(PORT_ISOPBDC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOP16 ,    (uint16)(PORT_ISOP16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU16 ,    (uint16)(PORT_ISOPU16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD16 ,    (uint16)(PORT_ISOPD16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC16 ,    (uint16)(PORT_ISOPODC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC16 ,    (uint16)(PORT_ISOPDSC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC17 ,    (uint16)(PORT_ISOPMC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM17 ,    (uint16)(PORT_ISOPM17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC17 ,    (uint16)(PORT_ISOPIPC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE17 ,    (uint16)(PORT_ISOPFCE17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC17 ,    (uint16)(PORT_ISOPFC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC17 ,    (uint16)(PORT_ISOPIBC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC17 ,    (uint16)(PORT_ISOPBDC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOP17 ,    (uint16)(PORT_ISOP17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU17 ,    (uint16)(PORT_ISOPU17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD17 ,    (uint16)(PORT_ISOPD17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC17 ,    (uint16)(PORT_ISOPODC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC17 ,    (uint16)(PORT_ISOPDSC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC21 ,    (uint16)(PORT_ISOPMC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM21 ,    (uint16)(PORT_ISOPM21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC21 ,    (uint16)(PORT_ISOPIPC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE21 ,    (uint16)(PORT_ISOPFCE21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC21 ,    (uint16)(PORT_ISOPFC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC21 ,    (uint16)(PORT_ISOPIBC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC21 ,    (uint16)(PORT_ISOPBDC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOP21 ,    (uint16)(PORT_ISOP21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU21 ,    (uint16)(PORT_ISOPU21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD21 ,    (uint16)(PORT_ISOPD21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC21 ,    (uint16)(PORT_ISOPODC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC21 ,    (uint16)(PORT_ISOPDSC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC42 ,    (uint16)(PORT_ISOPMC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM42 ,    (uint16)(PORT_ISOPM42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC42 ,    (uint16)(PORT_ISOPIPC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE42 ,    (uint16)(PORT_ISOPFCE42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC42 ,    (uint16)(PORT_ISOPFC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC42 ,    (uint16)(PORT_ISOPIBC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC42 ,    (uint16)(PORT_ISOPBDC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOP42 ,    (uint16)(PORT_ISOP42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU42 ,    (uint16)(PORT_ISOPU42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD42 ,    (uint16)(PORT_ISOPD42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC42 ,    (uint16)(PORT_ISOPODC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC42 ,    (uint16)(PORT_ISOPDSC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC43 ,    (uint16)(PORT_ISOPMC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM43 ,    (uint16)(PORT_ISOPM43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC43 ,    (uint16)(PORT_ISOPIPC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE43 ,    (uint16)(PORT_ISOPFCE43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC43 ,    (uint16)(PORT_ISOPFC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC43 ,    (uint16)(PORT_ISOPIBC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC43 ,    (uint16)(PORT_ISOPBDC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOP43 ,    (uint16)(PORT_ISOP43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU43 ,    (uint16)(PORT_ISOPU43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD43 ,    (uint16)(PORT_ISOPD43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC43 ,    (uint16)(PORT_ISOPODC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC43 ,    (uint16)(PORT_ISOPDSC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC44 ,    (uint16)(PORT_ISOPMC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM44 ,    (uint16)(PORT_ISOPM44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC44 ,    (uint16)(PORT_ISOPIPC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE44 ,    (uint16)(PORT_ISOPFCE44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC44 ,    (uint16)(PORT_ISOPFC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC44 ,    (uint16)(PORT_ISOPIBC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC44 ,    (uint16)(PORT_ISOPBDC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOP44 ,    (uint16)(PORT_ISOP44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU44 ,    (uint16)(PORT_ISOPU44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD44 ,    (uint16)(PORT_ISOPD44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC44 ,    (uint16)(PORT_ISOPODC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC44 ,    (uint16)(PORT_ISOPDSC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC45 ,    (uint16)(PORT_ISOPMC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM45 ,    (uint16)(PORT_ISOPM45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC45 ,    (uint16)(PORT_ISOPIPC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE45 ,    (uint16)(PORT_ISOPFCE45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC45 ,    (uint16)(PORT_ISOPFC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC45 ,    (uint16)(PORT_ISOPIBC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC45 ,    (uint16)(PORT_ISOPBDC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOP45 ,    (uint16)(PORT_ISOP45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU45 ,    (uint16)(PORT_ISOPU45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD45 ,    (uint16)(PORT_ISOPD45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC45 ,    (uint16)(PORT_ISOPODC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC45 ,    (uint16)(PORT_ISOPDSC45_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPMC0 ,    (uint16)(PORTJ_AWOJPMC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPM0 ,    (uint16)(PORTJ_AWOJPM0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPIPC0 ,    (uint16)(PORTJ_AWOJPIPC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPFCE0 ,    (uint16)(PORTJ_AWOJPFCE0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPFC0 ,    (uint16)(PORTJ_AWOJPFC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPIBC0 ,    (uint16)(PORTJ_AWOJPIBC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPBDC0 ,    (uint16)(PORTJ_AWOJPBDC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJP0 ,    (uint16)(PORTJ_AWOJP0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPU0 ,    (uint16)(PORTJ_AWOJPU0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPD0 ,    (uint16)(PORTJ_AWOJPD0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPODC0 ,    (uint16)(PORTJ_AWOJPODC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPDSC0 ,    (uint16)(PORTJ_AWOJPDSC0_SLEEP) }, \
/***************************************************************************
**
** Description:     RH850 D1M1H Port Pin Register Map List generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-14 19:26:51
***************************************************************************/
#define      PORT_PIN_REG16_LIST     \
{ PORT0_0, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_0)   }, \
{ PORT0_1, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_1)   }, \
{ PORT0_2, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_2)   }, \
{ PORT0_3, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_3)   }, \
{ PORT0_4, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_4)   }, \
{ PORT0_5, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_5)   }, \
{ PORT0_6, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_6)   }, \
{ PORT0_7, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_7)   }, \
{ PORT0_8, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_8)   }, \
{ PORT0_9, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0,  (uint16)(BIT_9)   }, \
\
{ PORT1_0, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1,  (uint16)(BIT_0)   }, \
{ PORT1_1, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1,  (uint16)(BIT_1)   }, \
{ PORT1_2, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1,  (uint16)(BIT_2)   }, \
{ PORT1_3, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1,  (uint16)(BIT_3)   }, \
{ PORT1_4, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1,  (uint16)(BIT_4)   }, \
{ PORT1_5, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1,  (uint16)(BIT_5)   }, \
\
{ PORT3_0, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_0)   }, \
{ PORT3_1, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_1)   }, \
{ PORT3_2, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_2)   }, \
{ PORT3_3, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_3)   }, \
{ PORT3_4, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_4)   }, \
{ PORT3_5, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_5)   }, \
{ PORT3_6, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_6)   }, \
{ PORT3_7, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_7)   }, \
{ PORT3_8, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_8)   }, \
{ PORT3_9, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3,  (uint16)(BIT_9)   }, \
\
{ PORT10_0, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_0)   }, \
{ PORT10_1, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_1)   }, \
{ PORT10_2, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_2)   }, \
{ PORT10_3, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_3)   }, \
{ PORT10_4, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_4)   }, \
{ PORT10_5, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_5)   }, \
{ PORT10_6, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_6)   }, \
{ PORT10_7, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_7)   }, \
{ PORT10_8, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_8)   }, \
{ PORT10_9, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_9)   }, \
{ PORT10_10, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_10)   }, \
{ PORT10_11, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10,  (uint16)(BIT_11)   }, \
\
{ PORT11_0, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) &PORT_ISOPFCE11,  (uint16)(BIT_0)   }, \
{ PORT11_1, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) &PORT_ISOPFCE11,  (uint16)(BIT_1)   }, \
{ PORT11_2, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) &PORT_ISOPFCE11,  (uint16)(BIT_2)   }, \
{ PORT11_3, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) &PORT_ISOPFCE11,  (uint16)(BIT_3)   }, \
\
{ PORT16_0, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_0)   }, \
{ PORT16_1, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_1)   }, \
{ PORT16_2, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_2)   }, \
{ PORT16_3, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_3)   }, \
{ PORT16_4, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_4)   }, \
{ PORT16_5, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_5)   }, \
{ PORT16_6, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_6)   }, \
{ PORT16_7, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_7)   }, \
{ PORT16_8, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_8)   }, \
{ PORT16_9, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_9)   }, \
{ PORT16_10, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_10)   }, \
{ PORT16_11, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16,  (uint16)(BIT_11)   }, \
\
{ PORT17_0, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_0)   }, \
{ PORT17_1, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_1)   }, \
{ PORT17_2, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_2)   }, \
{ PORT17_3, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_3)   }, \
{ PORT17_4, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_4)   }, \
{ PORT17_5, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_5)   }, \
{ PORT17_6, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_6)   }, \
{ PORT17_7, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_7)   }, \
{ PORT17_8, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_8)   }, \
{ PORT17_9, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_9)   }, \
{ PORT17_10, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_10)   }, \
{ PORT17_11, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17,  (uint16)(BIT_11)   }, \
\
{ PORT21_0, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_0)   }, \
{ PORT21_1, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_1)   }, \
{ PORT21_2, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_2)   }, \
{ PORT21_3, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_3)   }, \
{ PORT21_4, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_4)   }, \
{ PORT21_5, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_5)   }, \
{ PORT21_6, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_6)   }, \
{ PORT21_7, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_7)   }, \
{ PORT21_8, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_8)   }, \
{ PORT21_9, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21,  (uint16)(BIT_9)   }, \
\
{ PORT42_0, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_0)   }, \
{ PORT42_1, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_1)   }, \
{ PORT42_2, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_2)   }, \
{ PORT42_3, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_3)   }, \
{ PORT42_4, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_4)   }, \
{ PORT42_5, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_5)   }, \
{ PORT42_6, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_6)   }, \
{ PORT42_7, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_7)   }, \
{ PORT42_8, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_8)   }, \
{ PORT42_9, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_9)   }, \
{ PORT42_10, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_10)   }, \
{ PORT42_11, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_11)   }, \
{ PORT42_12, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_12)   }, \
{ PORT42_13, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_13)   }, \
{ PORT42_14, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_14)   }, \
{ PORT42_15, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42,  (uint16)(BIT_15)   }, \
\
{ PORT43_0, (uint16 *) &PORT_ISOPMC43 , (uint16 *) &PORT_ISOPM43, (uint16 *) &PORT_ISOPFC43, (uint16 *) &PORT_ISOPFCE43,  (uint16)(BIT_0)   }, \
{ PORT43_1, (uint16 *) &PORT_ISOPMC43 , (uint16 *) &PORT_ISOPM43, (uint16 *) &PORT_ISOPFC43, (uint16 *) &PORT_ISOPFCE43,  (uint16)(BIT_1)   }, \
\
{ PORT44_0, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_0)   }, \
{ PORT44_1, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_1)   }, \
{ PORT44_2, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_2)   }, \
{ PORT44_3, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_3)   }, \
{ PORT44_4, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_4)   }, \
{ PORT44_5, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_5)   }, \
{ PORT44_6, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_6)   }, \
{ PORT44_7, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_7)   }, \
{ PORT44_8, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_8)   }, \
{ PORT44_9, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_9)   }, \
{ PORT44_10, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_10)   }, \
{ PORT44_11, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44,  (uint16)(BIT_11)   }, \
\
{ PORT45_0, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_0)   }, \
{ PORT45_1, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_1)   }, \
{ PORT45_2, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_2)   }, \
{ PORT45_3, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_3)   }, \
{ PORT45_4, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_4)   }, \
{ PORT45_5, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_5)   }, \
{ PORT45_6, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_6)   }, \
{ PORT45_7, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_7)   }, \
{ PORT45_8, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_8)   }, \
{ PORT45_9, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_9)   }, \
{ PORT45_10, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_10)   }, \
{ PORT45_11, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_11)   }, \
{ PORT45_12, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_12)   }, \
{ PORT45_13, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45,  (uint16)(BIT_13)   }, \
\
{ JPORT0_0, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0,  (uint16)(BIT_0)   }, \
{ JPORT0_1, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0,  (uint16)(BIT_1)   }, \
{ JPORT0_2, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0,  (uint16)(BIT_2)   }, \
{ JPORT0_3, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0,  (uint16)(BIT_3)   }, \
{ JPORT0_4, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0,  (uint16)(BIT_4)   }, \
