/******************************************************************************
**  (c) copyright 2016
**  Company       O-film
**                All rights reserved
**  Secrecy Level STRICTLY CONFIDENTIAL
*******************************************************************************
**
**          File  : Port_Cfg.h
**          Description: RH850D1M1H_176Pin port IO configuration file, generated by tool automatically.
**                           Don't modify it manually.
**          Author:  jiangyuchang
**          Porting: niujianlong
**
**          Date  : 2016-07-29 19:58:12
**
**
******************************************************************************/
#ifndef PORT_CFG_H
#define PORT_CFG_H

/******************************************************************************
**    INCLUDES
******************************************************************************/
#include "board.h"
#include "device.h"


/******************************************************************************
**    MACROS
******************************************************************************/

/*****************PORT GROUP 0 INIT CONFIGURATION**********************/
#define       PORT_AWOPMC0_INIT                            (0x00F2u)
#define       PORT_AWOPM0_INIT                            (0x01A3u)
#define       PORT_AWOPIPC0_INIT                            (0x0000u)
#define       PORT_AWOPFCE0_INIT                            (0x00F0u)
#define       PORT_AWOPFC0_INIT                            (0x00F0u)
#define       PORT_AWOPIBC0_INIT                            (0x0101u)
#define       PORT_AWOPBDC0_INIT                            (0x0000u)
#define       PORT_AWOP0_INIT                            (0x000Cu)
#define       PORT_AWOPU0_INIT                            (0x0000u)
#define       PORT_AWOPD0_INIT                            (0x0000u)
#define       PORT_AWOPODC0_INIT                            (0x0000u)
#define       PORT_AWOPDSC0_INIT                            (0x0000u)

/*****************PORT GROUP 1 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC1_INIT                            (0x002Du)
#define       PORT_ISOPM1_INIT                            (0x0000u)
#define       PORT_ISOPIPC1_INIT                            (0x0000u)
#define       PORT_ISOPFCE1_INIT                            (0x0000u)
#define       PORT_ISOPFC1_INIT                            (0x0000u)
#define       PORT_ISOPIBC1_INIT                            (0x0000u)
#define       PORT_ISOPBDC1_INIT                            (0x0000u)
#define       PORT_ISOP1_INIT                            (0x003Fu)
#define       PORT_ISOPU1_INIT                            (0x0000u)
#define       PORT_ISOPD1_INIT                            (0x0000u)
#define       PORT_ISOPODC1_INIT                            (0x0000u)
#define       PORT_ISOPDSC1_INIT                            (0x0000u)

/*****************PORT GROUP 3 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC3_INIT                            (0x037Bu)
#define       PORT_ISOPM3_INIT                            (0x0004u)
#define       PORT_ISOPIPC3_INIT                            (0x0000u)
#define       PORT_ISOPFCE3_INIT                            (0x0300u)
#define       PORT_ISOPFC3_INIT                            (0x0278u)
#define       PORT_ISOPIBC3_INIT                            (0x0004u)
#define       PORT_ISOPBDC3_INIT                            (0x0000u)
#define       PORT_ISOP3_INIT                            (0x0278u)
#define       PORT_ISOPU3_INIT                            (0x0000u)
#define       PORT_ISOPD3_INIT                            (0x0000u)
#define       PORT_ISOPODC3_INIT                            (0x0000u)
#define       PORT_ISOPDSC3_INIT                            (0x0000u)

/*****************PORT GROUP 10 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC10_INIT                            (0x0000u)
#define       PORT_ISOPM10_INIT                            (0x01FFu)
#define       PORT_ISOPIPC10_INIT                            (0x0000u)
#define       PORT_ISOPFCE10_INIT                            (0x0000u)
#define       PORT_ISOPFC10_INIT                            (0x0000u)
#define       PORT_ISOPIBC10_INIT                            (0x0DFFu)
#define       PORT_ISOPBDC10_INIT                            (0x0000u)
#define       PORT_ISOP10_INIT                            (0x0C00u)
#define       PORT_ISOPU10_INIT                            (0x0000u)
#define       PORT_ISOPD10_INIT                            (0x0000u)
#define       PORT_ISOPODC10_INIT                            (0x0000u)
#define       PORT_ISOPDSC10_INIT                            (0x0000u)

/*****************PORT GROUP 11 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC11_INIT                            (0x0001u)
#define       PORT_ISOPM11_INIT                            (0x0003u)
#define       PORT_ISOPIPC11_INIT                            (0x0000u)
#define       PORT_ISOPFCE11_INIT                            (0x0000u)
#define       PORT_ISOPFC11_INIT                            (0x0001u)
#define       PORT_ISOPIBC11_INIT                            (0x0002u)
#define       PORT_ISOPBDC11_INIT                            (0x0000u)
#define       PORT_ISOP11_INIT                            (0x000Cu)
#define       PORT_ISOPU11_INIT                            (0x0000u)
#define       PORT_ISOPD11_INIT                            (0x0000u)
#define       PORT_ISOPODC11_INIT                            (0x0000u)
#define       PORT_ISOPDSC11_INIT                            (0x0000u)

/*****************PORT GROUP 16 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC16_INIT                            (0x0FFFu)
#define       PORT_ISOPM16_INIT                            (0x0000u)
#define       PORT_ISOPIPC16_INIT                            (0x0000u)
#define       PORT_ISOPFCE16_INIT                            (0x0000u)
#define       PORT_ISOPFC16_INIT                            (0x0000u)
#define       PORT_ISOPIBC16_INIT                            (0x0000u)
#define       PORT_ISOPBDC16_INIT                            (0x0000u)
#define       PORT_ISOP16_INIT                            (0x0FFFu)
#define       PORT_ISOPU16_INIT                            (0x0000u)
#define       PORT_ISOPD16_INIT                            (0x0000u)
#define       PORT_ISOPODC16_INIT                            (0x0000u)
#define       PORT_ISOPDSC16_INIT                            (0x0000u)

/*****************PORT GROUP 17 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC17_INIT                            (0x017Cu)
#define       PORT_ISOPM17_INIT                            (0x0C81u)
#define       PORT_ISOPIPC17_INIT                            (0x0000u)
#define       PORT_ISOPFCE17_INIT                            (0x0000u)
#define       PORT_ISOPFC17_INIT                            (0x017Cu)
#define       PORT_ISOPIBC17_INIT                            (0x0C81u)
#define       PORT_ISOPBDC17_INIT                            (0x0000u)
#define       PORT_ISOP17_INIT                            (0x037Cu)
#define       PORT_ISOPU17_INIT                            (0x0000u)
#define       PORT_ISOPD17_INIT                            (0x0000u)
#define       PORT_ISOPODC17_INIT                            (0x0000u)
#define       PORT_ISOPDSC17_INIT                            (0x0000u)

/*****************PORT GROUP 21 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC21_INIT                            (0x003Fu)
#define       PORT_ISOPM21_INIT                            (0x033Cu)
#define       PORT_ISOPIPC21_INIT                            (0x0000u)
#define       PORT_ISOPFCE21_INIT                            (0x0000u)
#define       PORT_ISOPFC21_INIT                            (0x0000u)
#define       PORT_ISOPIBC21_INIT                            (0x033Cu)
#define       PORT_ISOPBDC21_INIT                            (0x0000u)
#define       PORT_ISOP21_INIT                            (0x00C1u)
#define       PORT_ISOPU21_INIT                            (0x0000u)
#define       PORT_ISOPD21_INIT                            (0x0000u)
#define       PORT_ISOPODC21_INIT                            (0x0000u)
#define       PORT_ISOPDSC21_INIT                            (0x0000u)

/*****************PORT GROUP 42 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC42_INIT                            (0x03FFu)
#define       PORT_ISOPM42_INIT                            (0x8000u)
#define       PORT_ISOPIPC42_INIT                            (0x0000u)
#define       PORT_ISOPFCE42_INIT                            (0x0000u)
#define       PORT_ISOPFC42_INIT                            (0x0000u)
#define       PORT_ISOPIBC42_INIT                            (0x8000u)
#define       PORT_ISOPBDC42_INIT                            (0x0000u)
#define       PORT_ISOP42_INIT                            (0x63FFu)
#define       PORT_ISOPU42_INIT                            (0x0000u)
#define       PORT_ISOPD42_INIT                            (0x0000u)
#define       PORT_ISOPODC42_INIT                            (0x0000u)
#define       PORT_ISOPDSC42_INIT                            (0x0000u)

/*****************PORT GROUP 43 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC43_INIT                            (0x0000u)
#define       PORT_ISOPM43_INIT                            (0x0000u)
#define       PORT_ISOPIPC43_INIT                            (0x0000u)
#define       PORT_ISOPFCE43_INIT                            (0x0000u)
#define       PORT_ISOPFC43_INIT                            (0x0000u)
#define       PORT_ISOPIBC43_INIT                            (0x0000u)
#define       PORT_ISOPBDC43_INIT                            (0x0000u)
#define       PORT_ISOP43_INIT                            (0x0003u)
#define       PORT_ISOPU43_INIT                            (0x0000u)
#define       PORT_ISOPD43_INIT                            (0x0000u)
#define       PORT_ISOPODC43_INIT                            (0x0000u)
#define       PORT_ISOPDSC43_INIT                            (0x0000u)

/*****************PORT GROUP 44 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC44_INIT                            (0x0FFFu)
#define       PORT_ISOPM44_INIT                            (0x0000u)
#define       PORT_ISOPIPC44_INIT                            (0x0000u)
#define       PORT_ISOPFCE44_INIT                            (0x0000u)
#define       PORT_ISOPFC44_INIT                            (0x0000u)
#define       PORT_ISOPIBC44_INIT                            (0x0000u)
#define       PORT_ISOPBDC44_INIT                            (0x0000u)
#define       PORT_ISOP44_INIT                            (0x0FFFu)
#define       PORT_ISOPU44_INIT                            (0x0000u)
#define       PORT_ISOPD44_INIT                            (0x0000u)
#define       PORT_ISOPODC44_INIT                            (0x0000u)
#define       PORT_ISOPDSC44_INIT                            (0x0000u)

/*****************PORT GROUP 45 INIT CONFIGURATION**********************/
#define       PORT_ISOPMC45_INIT                            (0x3FFFu)
#define       PORT_ISOPM45_INIT                            (0x0000u)
#define       PORT_ISOPIPC45_INIT                            (0x0000u)
#define       PORT_ISOPFCE45_INIT                            (0x0002u)
#define       PORT_ISOPFC45_INIT                            (0x0002u)
#define       PORT_ISOPIBC45_INIT                            (0x0000u)
#define       PORT_ISOPBDC45_INIT                            (0x0000u)
#define       PORT_ISOP45_INIT                            (0x3FFFu)
#define       PORT_ISOPU45_INIT                            (0x0000u)
#define       PORT_ISOPD45_INIT                            (0x0000u)
#define       PORT_ISOPODC45_INIT                            (0x0000u)
#define       PORT_ISOPDSC45_INIT                            (0x0000u)

/*****************JPORT GROUP 0 INIT CONFIGURATION**********************/
#define       PORTJ_AWOJPMC0_INIT                            (0x0000u)
#define       PORTJ_AWOJPM0_INIT                            (0x0000u)
#define       PORTJ_AWOJPIPC0_INIT                            (0x0000u)
#define       PORTJ_AWOJPFCE0_INIT                            (0x0000u)
#define       PORTJ_AWOJPFC0_INIT                            (0x0000u)
#define       PORTJ_AWOJPIBC0_INIT                            (0x0000u)
#define       PORTJ_AWOJPBDC0_INIT                            (0x0000u)
#define       PORTJ_AWOJP0_INIT                            (0x0000u)
#define       PORTJ_AWOJPU0_INIT                            (0x0000u)
#define       PORTJ_AWOJPD0_INIT                            (0x0000u)
#define       PORTJ_AWOJPODC0_INIT                            (0x0000u)
#define       PORTJ_AWOJPDSC0_INIT                            (0x0000u)

/*****************PORT GROUP 0 SLEEP CONFIGURATION**********************/
#define       PORT_AWOPMC0_SLEEP                            (0x00A3u)
#define       PORT_AWOPM0_SLEEP                            (0x01A3u)
#define       PORT_AWOPIPC0_SLEEP                            (0x0000u)
#define       PORT_AWOPFCE0_SLEEP                            (0x00A0u)
#define       PORT_AWOPFC0_SLEEP                            (0x00A0u)
#define       PORT_AWOPIBC0_SLEEP                            (0x0000u)
#define       PORT_AWOPBDC0_SLEEP                            (0x0000u)
#define       PORT_AWOP0_SLEEP                            (0x0000u)
#define       PORT_AWOPU0_SLEEP                            (0x0000u)
#define       PORT_AWOPD0_SLEEP                            (0x0000u)
#define       PORT_AWOPODC0_SLEEP                            (0x0000u)
#define       PORT_AWOPDSC0_SLEEP                            (0x0000u)

/*****************PORT GROUP 1 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC1_SLEEP                            (0x0000u)
#define       PORT_ISOPM1_SLEEP                            (0x0000u)
#define       PORT_ISOPIPC1_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE1_SLEEP                            (0x0000u)
#define       PORT_ISOPFC1_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC1_SLEEP                            (0x0000u)
#define       PORT_ISOPBDC1_SLEEP                            (0x0000u)
#define       PORT_ISOP1_SLEEP                            (0x0000u)
#define       PORT_ISOPU1_SLEEP                            (0x0000u)
#define       PORT_ISOPD1_SLEEP                            (0x0000u)
#define       PORT_ISOPODC1_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC1_SLEEP                            (0x0000u)

/*****************PORT GROUP 3 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC3_SLEEP                            (0x0000u)
#define       PORT_ISOPM3_SLEEP                            (0x0005u)
#define       PORT_ISOPIPC3_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE3_SLEEP                            (0x0000u)
#define       PORT_ISOPFC3_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC3_SLEEP                            (0x0004u)
#define       PORT_ISOPBDC3_SLEEP                            (0x0000u)
#define       PORT_ISOP3_SLEEP                            (0x0080u)
#define       PORT_ISOPU3_SLEEP                            (0x0000u)
#define       PORT_ISOPD3_SLEEP                            (0x0000u)
#define       PORT_ISOPODC3_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC3_SLEEP                            (0x0000u)

/*****************PORT GROUP 10 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC10_SLEEP                            (0x0000u)
#define       PORT_ISOPM10_SLEEP                            (0x01FFu)
#define       PORT_ISOPIPC10_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE10_SLEEP                            (0x0000u)
#define       PORT_ISOPFC10_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC10_SLEEP                            (0x01FFu)
#define       PORT_ISOPBDC10_SLEEP                            (0x0000u)
#define       PORT_ISOP10_SLEEP                            (0x0000u)
#define       PORT_ISOPU10_SLEEP                            (0x0000u)
#define       PORT_ISOPD10_SLEEP                            (0x0000u)
#define       PORT_ISOPODC10_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC10_SLEEP                            (0x0000u)

/*****************PORT GROUP 11 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC11_SLEEP                            (0x0000u)
#define       PORT_ISOPM11_SLEEP                            (0x0003u)
#define       PORT_ISOPIPC11_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE11_SLEEP                            (0x0000u)
#define       PORT_ISOPFC11_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC11_SLEEP                            (0x0000u)
#define       PORT_ISOPBDC11_SLEEP                            (0x0000u)
#define       PORT_ISOP11_SLEEP                            (0x0000u)
#define       PORT_ISOPU11_SLEEP                            (0x0000u)
#define       PORT_ISOPD11_SLEEP                            (0x0000u)
#define       PORT_ISOPODC11_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC11_SLEEP                            (0x0000u)

/*****************PORT GROUP 16 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC16_SLEEP                            (0x0000u)
#define       PORT_ISOPM16_SLEEP                            (0x0000u)
#define       PORT_ISOPIPC16_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE16_SLEEP                            (0x0000u)
#define       PORT_ISOPFC16_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC16_SLEEP                            (0x0000u)
#define       PORT_ISOPBDC16_SLEEP                            (0x0000u)
#define       PORT_ISOP16_SLEEP                            (0x0000u)
#define       PORT_ISOPU16_SLEEP                            (0x0000u)
#define       PORT_ISOPD16_SLEEP                            (0x0000u)
#define       PORT_ISOPODC16_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC16_SLEEP                            (0x0000u)

/*****************PORT GROUP 17 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC17_SLEEP                            (0x0000u)
#define       PORT_ISOPM17_SLEEP                            (0x0C81u)
#define       PORT_ISOPIPC17_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE17_SLEEP                            (0x0000u)
#define       PORT_ISOPFC17_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC17_SLEEP                            (0x0C81u)
#define       PORT_ISOPBDC17_SLEEP                            (0x0000u)
#define       PORT_ISOP17_SLEEP                            (0x0002u)
#define       PORT_ISOPU17_SLEEP                            (0x0000u)
#define       PORT_ISOPD17_SLEEP                            (0x0000u)
#define       PORT_ISOPODC17_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC17_SLEEP                            (0x0000u)

/*****************PORT GROUP 21 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC21_SLEEP                            (0x0000u)
#define       PORT_ISOPM21_SLEEP                            (0x0300u)
#define       PORT_ISOPIPC21_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE21_SLEEP                            (0x0000u)
#define       PORT_ISOPFC21_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC21_SLEEP                            (0x0300u)
#define       PORT_ISOPBDC21_SLEEP                            (0x0000u)
#define       PORT_ISOP21_SLEEP                            (0x0002u)
#define       PORT_ISOPU21_SLEEP                            (0x0000u)
#define       PORT_ISOPD21_SLEEP                            (0x0000u)
#define       PORT_ISOPODC21_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC21_SLEEP                            (0x0000u)

/*****************PORT GROUP 42 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC42_SLEEP                            (0x0000u)
#define       PORT_ISOPM42_SLEEP                            (0xFC00u)
#define       PORT_ISOPIPC42_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE42_SLEEP                            (0x0000u)
#define       PORT_ISOPFC42_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC42_SLEEP                            (0xFC00u)
#define       PORT_ISOPBDC42_SLEEP                            (0x0000u)
#define       PORT_ISOP42_SLEEP                            (0x0000u)
#define       PORT_ISOPU42_SLEEP                            (0x0000u)
#define       PORT_ISOPD42_SLEEP                            (0x0000u)
#define       PORT_ISOPODC42_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC42_SLEEP                            (0x0000u)

/*****************PORT GROUP 43 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC43_SLEEP                            (0x0000u)
#define       PORT_ISOPM43_SLEEP                            (0x0000u)
#define       PORT_ISOPIPC43_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE43_SLEEP                            (0x0000u)
#define       PORT_ISOPFC43_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC43_SLEEP                            (0x0000u)
#define       PORT_ISOPBDC43_SLEEP                            (0x0000u)
#define       PORT_ISOP43_SLEEP                            (0x0000u)
#define       PORT_ISOPU43_SLEEP                            (0x0000u)
#define       PORT_ISOPD43_SLEEP                            (0x0000u)
#define       PORT_ISOPODC43_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC43_SLEEP                            (0x0000u)

/*****************PORT GROUP 44 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC44_SLEEP                            (0x0000u)
#define       PORT_ISOPM44_SLEEP                            (0x0000u)
#define       PORT_ISOPIPC44_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE44_SLEEP                            (0x0000u)
#define       PORT_ISOPFC44_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC44_SLEEP                            (0x0000u)
#define       PORT_ISOPBDC44_SLEEP                            (0x0000u)
#define       PORT_ISOP44_SLEEP                            (0x0000u)
#define       PORT_ISOPU44_SLEEP                            (0x0000u)
#define       PORT_ISOPD44_SLEEP                            (0x0000u)
#define       PORT_ISOPODC44_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC44_SLEEP                            (0x0000u)

/*****************PORT GROUP 45 SLEEP CONFIGURATION**********************/
#define       PORT_ISOPMC45_SLEEP                            (0x0000u)
#define       PORT_ISOPM45_SLEEP                            (0x0000u)
#define       PORT_ISOPIPC45_SLEEP                            (0x0000u)
#define       PORT_ISOPFCE45_SLEEP                            (0x0000u)
#define       PORT_ISOPFC45_SLEEP                            (0x0000u)
#define       PORT_ISOPIBC45_SLEEP                            (0x0000u)
#define       PORT_ISOPBDC45_SLEEP                            (0x0000u)
#define       PORT_ISOP45_SLEEP                            (0x0000u)
#define       PORT_ISOPU45_SLEEP                            (0x0000u)
#define       PORT_ISOPD45_SLEEP                            (0x0000u)
#define       PORT_ISOPODC45_SLEEP                            (0x0000u)
#define       PORT_ISOPDSC45_SLEEP                            (0x0000u)

/*****************JPORT GROUP 0 SLEEP CONFIGURATION**********************/
#define       PORTJ_AWOJPMC0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPM0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPIPC0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPFCE0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPFC0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPIBC0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPBDC0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJP0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPU0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPD0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPODC0_SLEEP                            (0x0000u)
#define       PORTJ_AWOJPDSC0_SLEEP                            (0x0000u)


/*****************PORT DIRECTION SETTING**********************/
#define      IGN_INT_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_0);SETBIT(PORT_AWOPM0, BIT_0);SETBIT(PORT_AWOPIBC0, BIT_0)
#define      IGN_INT_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_0);CLEARBIT(PORT_AWOPM0, BIT_0)
#define      FLMD1_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_1);SETBIT(PORT_AWOPM0, BIT_1);SETBIT(PORT_AWOPIBC0, BIT_1)
#define      FLMD1_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_1);CLEARBIT(PORT_AWOPM0, BIT_1)
#define      HW_O_M_CAN_STB_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_2);SETBIT(PORT_AWOPM0, BIT_2);SETBIT(PORT_AWOPIBC0, BIT_2)
#define      HW_O_M_CAN_STB_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_2);CLEARBIT(PORT_AWOPM0, BIT_2)
#define      HW_O_M_CAN_EN_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_3);SETBIT(PORT_AWOPM0, BIT_3);SETBIT(PORT_AWOPIBC0, BIT_3)
#define      HW_O_M_CAN_EN_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_3);CLEARBIT(PORT_AWOPM0, BIT_3)
#define      M_CAN_TX_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_4);SETBIT(PORT_AWOPM0, BIT_4);SETBIT(PORT_AWOPIBC0, BIT_4)
#define      M_CAN_TX_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_4);CLEARBIT(PORT_AWOPM0, BIT_4)
#define      M_CAN_RX_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_5);SETBIT(PORT_AWOPM0, BIT_5);SETBIT(PORT_AWOPIBC0, BIT_5)
#define      M_CAN_RX_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_5);CLEARBIT(PORT_AWOPM0, BIT_5)
#define      V_CAN_TX_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_6);SETBIT(PORT_AWOPM0, BIT_6);SETBIT(PORT_AWOPIBC0, BIT_6)
#define      V_CAN_TX_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_6);CLEARBIT(PORT_AWOPM0, BIT_6)
#define      V_CAN_RX_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_7);SETBIT(PORT_AWOPM0, BIT_7);SETBIT(PORT_AWOPIBC0, BIT_7)
#define      V_CAN_RX_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_7);CLEARBIT(PORT_AWOPM0, BIT_7)
#define      M_CAN_ERR_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_8);SETBIT(PORT_AWOPM0, BIT_8);SETBIT(PORT_AWOPIBC0, BIT_8)
#define      M_CAN_ERR_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_8);CLEARBIT(PORT_AWOPM0, BIT_8)
#define      TELLTALE_SPI_CS_SET_TO_INPUT()          CLEARBIT(PORT_AWOPMC0, BIT_9);SETBIT(PORT_AWOPM0, BIT_9);SETBIT(PORT_AWOPIBC0, BIT_9)
#define      TELLTALE_SPI_CS_SET_TO_OUTPUT()          CLEARBIT(PORT_AWOPMC0, BIT_9);CLEARBIT(PORT_AWOPM0, BIT_9)

#define      LED_SPI_DATA_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC1, BIT_0);SETBIT(PORT_ISOPM1, BIT_0);SETBIT(PORT_ISOPIBC1, BIT_0)
#define      LED_SPI_DATA_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC1, BIT_0);CLEARBIT(PORT_ISOPM1, BIT_0)
#define      LED_SPI_LATCH_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC1, BIT_1);SETBIT(PORT_ISOPM1, BIT_1);SETBIT(PORT_ISOPIBC1, BIT_1)
#define      LED_SPI_LATCH_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC1, BIT_1);CLEARBIT(PORT_ISOPM1, BIT_1)
#define      LED_SPI_CLK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC1, BIT_2);SETBIT(PORT_ISOPM1, BIT_2);SETBIT(PORT_ISOPIBC1, BIT_2)
#define      LED_SPI_CLK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC1, BIT_2);CLEARBIT(PORT_ISOPM1, BIT_2)
#define      TELLTALE_SPI_DATA_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC1, BIT_3);SETBIT(PORT_ISOPM1, BIT_3);SETBIT(PORT_ISOPIBC1, BIT_3)
#define      TELLTALE_SPI_DATA_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC1, BIT_3);CLEARBIT(PORT_ISOPM1, BIT_3)
#define      TELLTALE_SPI_LATCH_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC1, BIT_4);SETBIT(PORT_ISOPM1, BIT_4);SETBIT(PORT_ISOPIBC1, BIT_4)
#define      TELLTALE_SPI_LATCH_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC1, BIT_4);CLEARBIT(PORT_ISOPM1, BIT_4)
#define      TELLTALE_SPI_CLK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC1, BIT_5);SETBIT(PORT_ISOPM1, BIT_5);SETBIT(PORT_ISOPIBC1, BIT_5)
#define      TELLTALE_SPI_CLK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC1, BIT_5);CLEARBIT(PORT_ISOPM1, BIT_5)

#define      VIDEO_SDA_MDIO_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_0);SETBIT(PORT_ISOPM3, BIT_0);SETBIT(PORT_ISOPIBC3, BIT_0)
#define      VIDEO_SDA_MDIO_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_0);CLEARBIT(PORT_ISOPM3, BIT_0)
#define      VIDEO_SCL_MDC_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_1);SETBIT(PORT_ISOPM3, BIT_1);SETBIT(PORT_ISOPIBC3, BIT_1)
#define      VIDEO_SCL_MDC_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_1);CLEARBIT(PORT_ISOPM3, BIT_1)
#define      ETNB_INT_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_2);SETBIT(PORT_ISOPM3, BIT_2);SETBIT(PORT_ISOPIBC3, BIT_2)
#define      ETNB_INT_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_2);CLEARBIT(PORT_ISOPM3, BIT_2)
#define      SPEAKER_I2S_TXD_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_3);SETBIT(PORT_ISOPM3, BIT_3);SETBIT(PORT_ISOPIBC3, BIT_3)
#define      SPEAKER_I2S_TXD_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_3);CLEARBIT(PORT_ISOPM3, BIT_3)
#define      SPEAKER_I2S_BIT_CLK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_4);SETBIT(PORT_ISOPM3, BIT_4);SETBIT(PORT_ISOPIBC3, BIT_4)
#define      SPEAKER_I2S_BIT_CLK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_4);CLEARBIT(PORT_ISOPM3, BIT_4)
#define      SPEAKER_I2S_WS_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_5);SETBIT(PORT_ISOPM3, BIT_5);SETBIT(PORT_ISOPIBC3, BIT_5)
#define      SPEAKER_I2S_WS_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_5);CLEARBIT(PORT_ISOPM3, BIT_5)
#define      SPEAKER_SYSCLK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_6);SETBIT(PORT_ISOPM3, BIT_6);SETBIT(PORT_ISOPIBC3, BIT_6)
#define      SPEAKER_SYSCLK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_6);CLEARBIT(PORT_ISOPM3, BIT_6)
#define      CODEC_MUTE_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_7);SETBIT(PORT_ISOPM3, BIT_7);SETBIT(PORT_ISOPIBC3, BIT_7)
#define      CODEC_MUTE_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_7);CLEARBIT(PORT_ISOPM3, BIT_7)
#define      SPEAKER_OUTPUT_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_8);SETBIT(PORT_ISOPM3, BIT_8);SETBIT(PORT_ISOPIBC3, BIT_8)
#define      SPEAKER_OUTPUT_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_8);CLEARBIT(PORT_ISOPM3, BIT_8)
#define      SS_CTRL_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC3, BIT_9);SETBIT(PORT_ISOPM3, BIT_9);SETBIT(PORT_ISOPIBC3, BIT_9)
#define      SS_CTRL_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC3, BIT_9);CLEARBIT(PORT_ISOPM3, BIT_9)

#define      TFT_THERMAL_MON_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_0);SETBIT(PORT_ISOPM10, BIT_0);SETBIT(PORT_ISOPIBC10, BIT_0)
#define      TFT_THERMAL_MON_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_0);CLEARBIT(PORT_ISOPM10, BIT_0)
#define      BAT_MON_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_1);SETBIT(PORT_ISOPM10, BIT_1);SETBIT(PORT_ISOPIBC10, BIT_1)
#define      BAT_MON_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_1);CLEARBIT(PORT_ISOPM10, BIT_1)
#define      SBATT_MON_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_2);SETBIT(PORT_ISOPM10, BIT_2);SETBIT(PORT_ISOPIBC10, BIT_2)
#define      SBATT_MON_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_2);CLEARBIT(PORT_ISOPM10, BIT_2)
#define      SW5V_MON_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_3);SETBIT(PORT_ISOPM10, BIT_3);SETBIT(PORT_ISOPIBC10, BIT_3)
#define      SW5V_MON_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_3);CLEARBIT(PORT_ISOPM10, BIT_3)
#define      FUEL_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_4);SETBIT(PORT_ISOPM10, BIT_4);SETBIT(PORT_ISOPIBC10, BIT_4)
#define      FUEL_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_4);CLEARBIT(PORT_ISOPM10, BIT_4)
#define      SW5V_REF_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_5);SETBIT(PORT_ISOPM10, BIT_5);SETBIT(PORT_ISOPIBC10, BIT_5)
#define      SW5V_REF_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_5);CLEARBIT(PORT_ISOPM10, BIT_5)
#define      STEERING_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_6);SETBIT(PORT_ISOPM10, BIT_6);SETBIT(PORT_ISOPIBC10, BIT_6)
#define      STEERING_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_6);CLEARBIT(PORT_ISOPM10, BIT_6)
#define      BACKLIGHT_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_7);SETBIT(PORT_ISOPM10, BIT_7);SETBIT(PORT_ISOPIBC10, BIT_7)
#define      BACKLIGHT_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_7);CLEARBIT(PORT_ISOPM10, BIT_7)
#define      AIRBAG_FB_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_8);SETBIT(PORT_ISOPM10, BIT_8);SETBIT(PORT_ISOPIBC10, BIT_8)
#define      AIRBAG_FB_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_8);CLEARBIT(PORT_ISOPM10, BIT_8)
#define      NO_USED_PIN_109_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_9);SETBIT(PORT_ISOPM10, BIT_9);SETBIT(PORT_ISOPIBC10, BIT_9)
#define      NO_USED_PIN_109_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_9);CLEARBIT(PORT_ISOPM10, BIT_9)
#define      SW5V_EN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_10);SETBIT(PORT_ISOPM10, BIT_10);SETBIT(PORT_ISOPIBC10, BIT_10)
#define      SW5V_EN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_10);CLEARBIT(PORT_ISOPM10, BIT_10)
#define      V_CAN_STB_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC10, BIT_11);SETBIT(PORT_ISOPM10, BIT_11);SETBIT(PORT_ISOPIBC10, BIT_11)
#define      V_CAN_STB_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC10, BIT_11);CLEARBIT(PORT_ISOPM10, BIT_11)

#define      RADA_CLK_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC11, BIT_0);SETBIT(PORT_ISOPM11, BIT_0);SETBIT(PORT_ISOPIBC11, BIT_0)
#define      RADA_CLK_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC11, BIT_0);CLEARBIT(PORT_ISOPM11, BIT_0)
#define      RADA_DATA_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC11, BIT_1);SETBIT(PORT_ISOPM11, BIT_1);SETBIT(PORT_ISOPIBC11, BIT_1)
#define      RADA_DATA_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC11, BIT_1);CLEARBIT(PORT_ISOPM11, BIT_1)
#define      SBATT_EN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC11, BIT_2);SETBIT(PORT_ISOPM11, BIT_2);SETBIT(PORT_ISOPIBC11, BIT_2)
#define      SBATT_EN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC11, BIT_2);CLEARBIT(PORT_ISOPM11, BIT_2)
#define      LEFT_TT_TT3_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC11, BIT_3);SETBIT(PORT_ISOPM11, BIT_3);SETBIT(PORT_ISOPIBC11, BIT_3)
#define      LEFT_TT_TT3_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC11, BIT_3);CLEARBIT(PORT_ISOPM11, BIT_3)

#define      SPEEDO_1P_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_0);SETBIT(PORT_ISOPM16, BIT_0);SETBIT(PORT_ISOPIBC16, BIT_0)
#define      SPEEDO_1P_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_0);CLEARBIT(PORT_ISOPM16, BIT_0)
#define      SPEEDO_1N_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_1);SETBIT(PORT_ISOPM16, BIT_1);SETBIT(PORT_ISOPIBC16, BIT_1)
#define      SPEEDO_1N_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_1);CLEARBIT(PORT_ISOPM16, BIT_1)
#define      SPEEDO_2P_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_2);SETBIT(PORT_ISOPM16, BIT_2);SETBIT(PORT_ISOPIBC16, BIT_2)
#define      SPEEDO_2P_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_2);CLEARBIT(PORT_ISOPM16, BIT_2)
#define      SPEEDO_2N_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_3);SETBIT(PORT_ISOPM16, BIT_3);SETBIT(PORT_ISOPIBC16, BIT_3)
#define      SPEEDO_2N_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_3);CLEARBIT(PORT_ISOPM16, BIT_3)
#define      TEMP_1P_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_4);SETBIT(PORT_ISOPM16, BIT_4);SETBIT(PORT_ISOPIBC16, BIT_4)
#define      TEMP_1P_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_4);CLEARBIT(PORT_ISOPM16, BIT_4)
#define      TEMP_1N_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_5);SETBIT(PORT_ISOPM16, BIT_5);SETBIT(PORT_ISOPIBC16, BIT_5)
#define      TEMP_1N_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_5);CLEARBIT(PORT_ISOPM16, BIT_5)
#define      TEMP_2P_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_6);SETBIT(PORT_ISOPM16, BIT_6);SETBIT(PORT_ISOPIBC16, BIT_6)
#define      TEMP_2P_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_6);CLEARBIT(PORT_ISOPM16, BIT_6)
#define      TEMP_2N_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_7);SETBIT(PORT_ISOPM16, BIT_7);SETBIT(PORT_ISOPIBC16, BIT_7)
#define      TEMP_2N_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_7);CLEARBIT(PORT_ISOPM16, BIT_7)
#define      FUEL_1P_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_8);SETBIT(PORT_ISOPM16, BIT_8);SETBIT(PORT_ISOPIBC16, BIT_8)
#define      FUEL_1P_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_8);CLEARBIT(PORT_ISOPM16, BIT_8)
#define      FUEL_1N_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_9);SETBIT(PORT_ISOPM16, BIT_9);SETBIT(PORT_ISOPIBC16, BIT_9)
#define      FUEL_1N_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_9);CLEARBIT(PORT_ISOPM16, BIT_9)
#define      FUEL_2P_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_10);SETBIT(PORT_ISOPM16, BIT_10);SETBIT(PORT_ISOPIBC16, BIT_10)
#define      FUEL_2P_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_10);CLEARBIT(PORT_ISOPM16, BIT_10)
#define      FUEL_2N_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC16, BIT_11);SETBIT(PORT_ISOPM16, BIT_11);SETBIT(PORT_ISOPIBC16, BIT_11)
#define      FUEL_2N_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC16, BIT_11);CLEARBIT(PORT_ISOPM16, BIT_11)

#define      CHARGE_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_0);SETBIT(PORT_ISOPM17, BIT_0);SETBIT(PORT_ISOPIBC17, BIT_0)
#define      CHARGE_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_0);CLEARBIT(PORT_ISOPM17, BIT_0)
#define      P3V3_SW_EN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_1);SETBIT(PORT_ISOPM17, BIT_1);SETBIT(PORT_ISOPIBC17, BIT_1)
#define      P3V3_SW_EN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_1);CLEARBIT(PORT_ISOPM17, BIT_1)
#define      LEFT_GAUGE_PWM_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_2);SETBIT(PORT_ISOPM17, BIT_2);SETBIT(PORT_ISOPIBC17, BIT_2)
#define      LEFT_GAUGE_PWM_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_2);CLEARBIT(PORT_ISOPM17, BIT_2)
#define      LEFT_POINTER_PWM_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_3);SETBIT(PORT_ISOPM17, BIT_3);SETBIT(PORT_ISOPIBC17, BIT_3)
#define      LEFT_POINTER_PWM_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_3);CLEARBIT(PORT_ISOPM17, BIT_3)
#define      RIGHT_POINTER_PWM_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_4);SETBIT(PORT_ISOPM17, BIT_4);SETBIT(PORT_ISOPIBC17, BIT_4)
#define      RIGHT_POINTER_PWM_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_4);CLEARBIT(PORT_ISOPM17, BIT_4)
#define      RIGHT_GAUGE_PWM_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_5);SETBIT(PORT_ISOPM17, BIT_5);SETBIT(PORT_ISOPIBC17, BIT_5)
#define      RIGHT_GAUGE_PWM_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_5);CLEARBIT(PORT_ISOPM17, BIT_5)
#define      TT_PWM_CTRL_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_6);SETBIT(PORT_ISOPM17, BIT_6);SETBIT(PORT_ISOPIBC17, BIT_6)
#define      TT_PWM_CTRL_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_6);CLEARBIT(PORT_ISOPM17, BIT_6)
#define      PARK_BRAKE_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_7);SETBIT(PORT_ISOPM17, BIT_7);SETBIT(PORT_ISOPIBC17, BIT_7)
#define      PARK_BRAKE_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_7);CLEARBIT(PORT_ISOPM17, BIT_7)
#define      TFT_BL_PWM_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_8);SETBIT(PORT_ISOPM17, BIT_8);SETBIT(PORT_ISOPIBC17, BIT_8)
#define      TFT_BL_PWM_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_8);CLEARBIT(PORT_ISOPM17, BIT_8)
#define      NIGHT_PANEL_CTRL_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_9);SETBIT(PORT_ISOPM17, BIT_9);SETBIT(PORT_ISOPIBC17, BIT_9)
#define      NIGHT_PANEL_CTRL_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_9);CLEARBIT(PORT_ISOPM17, BIT_9)
#define      WASH_FLUID_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_10);SETBIT(PORT_ISOPM17, BIT_10);SETBIT(PORT_ISOPIBC17, BIT_10)
#define      WASH_FLUID_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_10);CLEARBIT(PORT_ISOPM17, BIT_10)
#define      BRAKE_FLUID_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC17, BIT_11);SETBIT(PORT_ISOPM17, BIT_11);SETBIT(PORT_ISOPIBC17, BIT_11)
#define      BRAKE_FLUID_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC17, BIT_11);CLEARBIT(PORT_ISOPM17, BIT_11)

#define      QSPI_SCK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_0);SETBIT(PORT_ISOPM21, BIT_0);SETBIT(PORT_ISOPIBC21, BIT_0)
#define      QSPI_SCK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_0);CLEARBIT(PORT_ISOPM21, BIT_0)
#define      QSPI_CS_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_1);SETBIT(PORT_ISOPM21, BIT_1);SETBIT(PORT_ISOPIBC21, BIT_1)
#define      QSPI_CS_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_1);CLEARBIT(PORT_ISOPM21, BIT_1)
#define      QSPI_IO0_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_2);SETBIT(PORT_ISOPM21, BIT_2);SETBIT(PORT_ISOPIBC21, BIT_2)
#define      QSPI_IO0_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_2);CLEARBIT(PORT_ISOPM21, BIT_2)
#define      QSPI_IO1_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_3);SETBIT(PORT_ISOPM21, BIT_3);SETBIT(PORT_ISOPIBC21, BIT_3)
#define      QSPI_IO1_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_3);CLEARBIT(PORT_ISOPM21, BIT_3)
#define      QSPI_IO2_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_4);SETBIT(PORT_ISOPM21, BIT_4);SETBIT(PORT_ISOPIBC21, BIT_4)
#define      QSPI_IO2_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_4);CLEARBIT(PORT_ISOPM21, BIT_4)
#define      QSPI_IO3_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_5);SETBIT(PORT_ISOPM21, BIT_5);SETBIT(PORT_ISOPIBC21, BIT_5)
#define      QSPI_IO3_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_5);CLEARBIT(PORT_ISOPM21, BIT_5)
#define      ETNB_RST_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_6);SETBIT(PORT_ISOPM21, BIT_6);SETBIT(PORT_ISOPIBC21, BIT_6)
#define      ETNB_RST_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_6);CLEARBIT(PORT_ISOPM21, BIT_6)
#define      ETNB_EN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_7);SETBIT(PORT_ISOPM21, BIT_7);SETBIT(PORT_ISOPIBC21, BIT_7)
#define      ETNB_EN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_7);CLEARBIT(PORT_ISOPM21, BIT_7)
#define      LOW_OIL_PRESSURE_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_8);SETBIT(PORT_ISOPM21, BIT_8);SETBIT(PORT_ISOPIBC21, BIT_8)
#define      LOW_OIL_PRESSURE_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_8);CLEARBIT(PORT_ISOPM21, BIT_8)
#define      NIGHT_PANNEL_IN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC21, BIT_9);SETBIT(PORT_ISOPM21, BIT_9);SETBIT(PORT_ISOPIBC21, BIT_9)
#define      NIGHT_PANNEL_IN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC21, BIT_9);CLEARBIT(PORT_ISOPM21, BIT_9)

#define      ETNB_TXD3_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_0);SETBIT(PORT_ISOPM42, BIT_0);SETBIT(PORT_ISOPIBC42, BIT_0)
#define      ETNB_TXD3_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_0);CLEARBIT(PORT_ISOPM42, BIT_0)
#define      ETNB_TXD2_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_1);SETBIT(PORT_ISOPM42, BIT_1);SETBIT(PORT_ISOPIBC42, BIT_1)
#define      ETNB_TXD2_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_1);CLEARBIT(PORT_ISOPM42, BIT_1)
#define      ETNB_TXD1_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_2);SETBIT(PORT_ISOPM42, BIT_2);SETBIT(PORT_ISOPIBC42, BIT_2)
#define      ETNB_TXD1_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_2);CLEARBIT(PORT_ISOPM42, BIT_2)
#define      ETNB_TXD0_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_3);SETBIT(PORT_ISOPM42, BIT_3);SETBIT(PORT_ISOPIBC42, BIT_3)
#define      ETNB_TXD0_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_3);CLEARBIT(PORT_ISOPM42, BIT_3)
#define      ETNB_TXEN_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_4);SETBIT(PORT_ISOPM42, BIT_4);SETBIT(PORT_ISOPIBC42, BIT_4)
#define      ETNB_TXEN_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_4);CLEARBIT(PORT_ISOPM42, BIT_4)
#define      ETNB_TXER_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_5);SETBIT(PORT_ISOPM42, BIT_5);SETBIT(PORT_ISOPIBC42, BIT_5)
#define      ETNB_TXER_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_5);CLEARBIT(PORT_ISOPM42, BIT_5)
#define      NO_USED_PIN426_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_6);SETBIT(PORT_ISOPM42, BIT_6);SETBIT(PORT_ISOPIBC42, BIT_6)
#define      NO_USED_PIN426_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_6);CLEARBIT(PORT_ISOPM42, BIT_6)
#define      NO_USED_PIN427_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_7);SETBIT(PORT_ISOPM42, BIT_7);SETBIT(PORT_ISOPIBC42, BIT_7)
#define      NO_USED_PIN427_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_7);CLEARBIT(PORT_ISOPM42, BIT_7)
#define      ETNB_TXCLK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_8);SETBIT(PORT_ISOPM42, BIT_8);SETBIT(PORT_ISOPIBC42, BIT_8)
#define      ETNB_TXCLK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_8);CLEARBIT(PORT_ISOPM42, BIT_8)
#define      ETNB_RXCLK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_9);SETBIT(PORT_ISOPM42, BIT_9);SETBIT(PORT_ISOPIBC42, BIT_9)
#define      ETNB_RXCLK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_9);CLEARBIT(PORT_ISOPM42, BIT_9)
#define      ETNB_RXD3_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_10);SETBIT(PORT_ISOPM42, BIT_10);SETBIT(PORT_ISOPIBC42, BIT_10)
#define      ETNB_RXD3_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_10);CLEARBIT(PORT_ISOPM42, BIT_10)
#define      ETNB_RXD2_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_11);SETBIT(PORT_ISOPM42, BIT_11);SETBIT(PORT_ISOPIBC42, BIT_11)
#define      ETNB_RXD2_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_11);CLEARBIT(PORT_ISOPM42, BIT_11)
#define      ETNB_RXD1_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_12);SETBIT(PORT_ISOPM42, BIT_12);SETBIT(PORT_ISOPIBC42, BIT_12)
#define      ETNB_RXD1_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_12);CLEARBIT(PORT_ISOPM42, BIT_12)
#define      ETNB_RXD0_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_13);SETBIT(PORT_ISOPM42, BIT_13);SETBIT(PORT_ISOPIBC42, BIT_13)
#define      ETNB_RXD0_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_13);CLEARBIT(PORT_ISOPM42, BIT_13)
#define      ETNB_RXDV_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_14);SETBIT(PORT_ISOPM42, BIT_14);SETBIT(PORT_ISOPIBC42, BIT_14)
#define      ETNB_RXDV_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_14);CLEARBIT(PORT_ISOPM42, BIT_14)
#define      ETNB_RXER_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC42, BIT_15);SETBIT(PORT_ISOPM42, BIT_15);SETBIT(PORT_ISOPIBC42, BIT_15)
#define      ETNB_RXER_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC42, BIT_15);CLEARBIT(PORT_ISOPM42, BIT_15)

#define      TFT_RESET_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC43, BIT_0);SETBIT(PORT_ISOPM43, BIT_0);SETBIT(PORT_ISOPIBC43, BIT_0)
#define      TFT_RESET_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC43, BIT_0);CLEARBIT(PORT_ISOPM43, BIT_0)
#define      TFT_STBYB_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC43, BIT_1);SETBIT(PORT_ISOPM43, BIT_1);SETBIT(PORT_ISOPIBC43, BIT_1)
#define      TFT_STBYB_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC43, BIT_1);CLEARBIT(PORT_ISOPM43, BIT_1)

#define      TFT_RED7_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_0);SETBIT(PORT_ISOPM44, BIT_0);SETBIT(PORT_ISOPIBC44, BIT_0)
#define      TFT_RED7_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_0);CLEARBIT(PORT_ISOPM44, BIT_0)
#define      TFT_RED6_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_1);SETBIT(PORT_ISOPM44, BIT_1);SETBIT(PORT_ISOPIBC44, BIT_1)
#define      TFT_RED6_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_1);CLEARBIT(PORT_ISOPM44, BIT_1)
#define      TFT_RED5_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_2);SETBIT(PORT_ISOPM44, BIT_2);SETBIT(PORT_ISOPIBC44, BIT_2)
#define      TFT_RED5_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_2);CLEARBIT(PORT_ISOPM44, BIT_2)
#define      TFT_RED4_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_3);SETBIT(PORT_ISOPM44, BIT_3);SETBIT(PORT_ISOPIBC44, BIT_3)
#define      TFT_RED4_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_3);CLEARBIT(PORT_ISOPM44, BIT_3)
#define      TFT_RED3_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_4);SETBIT(PORT_ISOPM44, BIT_4);SETBIT(PORT_ISOPIBC44, BIT_4)
#define      TFT_RED3_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_4);CLEARBIT(PORT_ISOPM44, BIT_4)
#define      TFT_RED2_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_5);SETBIT(PORT_ISOPM44, BIT_5);SETBIT(PORT_ISOPIBC44, BIT_5)
#define      TFT_RED2_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_5);CLEARBIT(PORT_ISOPM44, BIT_5)
#define      TFT_RED1_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_6);SETBIT(PORT_ISOPM44, BIT_6);SETBIT(PORT_ISOPIBC44, BIT_6)
#define      TFT_RED1_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_6);CLEARBIT(PORT_ISOPM44, BIT_6)
#define      TFT_RED0_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_7);SETBIT(PORT_ISOPM44, BIT_7);SETBIT(PORT_ISOPIBC44, BIT_7)
#define      TFT_RED0_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_7);CLEARBIT(PORT_ISOPM44, BIT_7)
#define      TFT_GREEN7_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_8);SETBIT(PORT_ISOPM44, BIT_8);SETBIT(PORT_ISOPIBC44, BIT_8)
#define      TFT_GREEN7_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_8);CLEARBIT(PORT_ISOPM44, BIT_8)
#define      TFT_GREEN6_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_9);SETBIT(PORT_ISOPM44, BIT_9);SETBIT(PORT_ISOPIBC44, BIT_9)
#define      TFT_GREEN6_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_9);CLEARBIT(PORT_ISOPM44, BIT_9)
#define      TFT_GREEN5_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_10);SETBIT(PORT_ISOPM44, BIT_10);SETBIT(PORT_ISOPIBC44, BIT_10)
#define      TFT_GREEN5_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_10);CLEARBIT(PORT_ISOPM44, BIT_10)
#define      TFT_GREEN4_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC44, BIT_11);SETBIT(PORT_ISOPM44, BIT_11);SETBIT(PORT_ISOPIBC44, BIT_11)
#define      TFT_GREEN4_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC44, BIT_11);CLEARBIT(PORT_ISOPM44, BIT_11)

#define      TFT_CLK_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_0);SETBIT(PORT_ISOPM45, BIT_0);SETBIT(PORT_ISOPIBC45, BIT_0)
#define      TFT_CLK_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_0);CLEARBIT(PORT_ISOPM45, BIT_0)
#define      TFT_DE_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_1);SETBIT(PORT_ISOPM45, BIT_1);SETBIT(PORT_ISOPIBC45, BIT_1)
#define      TFT_DE_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_1);CLEARBIT(PORT_ISOPM45, BIT_1)
#define      TFT_GREEN3_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_2);SETBIT(PORT_ISOPM45, BIT_2);SETBIT(PORT_ISOPIBC45, BIT_2)
#define      TFT_GREEN3_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_2);CLEARBIT(PORT_ISOPM45, BIT_2)
#define      TFT_GREEN2_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_3);SETBIT(PORT_ISOPM45, BIT_3);SETBIT(PORT_ISOPIBC45, BIT_3)
#define      TFT_GREEN2_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_3);CLEARBIT(PORT_ISOPM45, BIT_3)
#define      TFT_GREEN1_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_4);SETBIT(PORT_ISOPM45, BIT_4);SETBIT(PORT_ISOPIBC45, BIT_4)
#define      TFT_GREEN1_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_4);CLEARBIT(PORT_ISOPM45, BIT_4)
#define      TFT_GREEN0_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_5);SETBIT(PORT_ISOPM45, BIT_5);SETBIT(PORT_ISOPIBC45, BIT_5)
#define      TFT_GREEN0_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_5);CLEARBIT(PORT_ISOPM45, BIT_5)
#define      TFT_BLUE7_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_6);SETBIT(PORT_ISOPM45, BIT_6);SETBIT(PORT_ISOPIBC45, BIT_6)
#define      TFT_BLUE7_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_6);CLEARBIT(PORT_ISOPM45, BIT_6)
#define      TFT_BLUE6_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_7);SETBIT(PORT_ISOPM45, BIT_7);SETBIT(PORT_ISOPIBC45, BIT_7)
#define      TFT_BLUE6_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_7);CLEARBIT(PORT_ISOPM45, BIT_7)
#define      TFT_BLUE5_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_8);SETBIT(PORT_ISOPM45, BIT_8);SETBIT(PORT_ISOPIBC45, BIT_8)
#define      TFT_BLUE5_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_8);CLEARBIT(PORT_ISOPM45, BIT_8)
#define      TFT_BLUE4_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_9);SETBIT(PORT_ISOPM45, BIT_9);SETBIT(PORT_ISOPIBC45, BIT_9)
#define      TFT_BLUE4_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_9);CLEARBIT(PORT_ISOPM45, BIT_9)
#define      TFT_BLUE3_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_10);SETBIT(PORT_ISOPM45, BIT_10);SETBIT(PORT_ISOPIBC45, BIT_10)
#define      TFT_BLUE3_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_10);CLEARBIT(PORT_ISOPM45, BIT_10)
#define      TFT_BLUE2_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_11);SETBIT(PORT_ISOPM45, BIT_11);SETBIT(PORT_ISOPIBC45, BIT_11)
#define      TFT_BLUE2_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_11);CLEARBIT(PORT_ISOPM45, BIT_11)
#define      TFT_BLUE1_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_12);SETBIT(PORT_ISOPM45, BIT_12);SETBIT(PORT_ISOPIBC45, BIT_12)
#define      TFT_BLUE1_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_12);CLEARBIT(PORT_ISOPM45, BIT_12)
#define      TFT_BLUE0_SET_TO_INPUT()          CLEARBIT(PORT_ISOPMC45, BIT_13);SETBIT(PORT_ISOPM45, BIT_13);SETBIT(PORT_ISOPIBC45, BIT_13)
#define      TFT_BLUE0_SET_TO_OUTPUT()          CLEARBIT(PORT_ISOPMC45, BIT_13);CLEARBIT(PORT_ISOPM45, BIT_13)

#define      TDI_SET_TO_INPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_0);SETBIT(PORTJ_AWOJPM0, BIT_0);SETBIT(PORTJ_AWOJPIBC0, BIT_0)
#define      TDI_SET_TO_OUTPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_0);CLEARBIT(PORTJ_AWOJPM0, BIT_0)
#define      TDO_SET_TO_INPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_1);SETBIT(PORTJ_AWOJPM0, BIT_1);SETBIT(PORTJ_AWOJPIBC0, BIT_1)
#define      TDO_SET_TO_OUTPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_1);CLEARBIT(PORTJ_AWOJPM0, BIT_1)
#define      TCK_SET_TO_INPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_2);SETBIT(PORTJ_AWOJPM0, BIT_2);SETBIT(PORTJ_AWOJPIBC0, BIT_2)
#define      TCK_SET_TO_OUTPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_2);CLEARBIT(PORTJ_AWOJPM0, BIT_2)
#define      TMS_SET_TO_INPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_3);SETBIT(PORTJ_AWOJPM0, BIT_3);SETBIT(PORTJ_AWOJPIBC0, BIT_3)
#define      TMS_SET_TO_OUTPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_3);CLEARBIT(PORTJ_AWOJPM0, BIT_3)
#define      TRST_SET_TO_INPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_4);SETBIT(PORTJ_AWOJPM0, BIT_4);SETBIT(PORTJ_AWOJPIBC0, BIT_4)
#define      TRST_SET_TO_OUTPUT()          CLEARBIT(PORTJ_AWOJPMC0, BIT_4);CLEARBIT(PORTJ_AWOJPM0, BIT_4)

/**************END OF PORT DIRECTION SETTING******************/


/************************************************************************
**
** Description:     RH850 D1M1H Port Init Register List generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-29 19:58:12
************************************************************************/
#define      PORT_INIT_REG16_LIST \
{ (uint16 *) &PORT_AWOPMC0 ,    (uint16)(PORT_AWOPMC0_INIT) }, \
{ (uint16 *) &PORT_AWOPM0 ,    (uint16)(PORT_AWOPM0_INIT) }, \
{ (uint16 *) &PORT_AWOPIPC0 ,    (uint16)(PORT_AWOPIPC0_INIT) }, \
{ (uint16 *) &PORT_AWOPFCE0 ,    (uint16)(PORT_AWOPFCE0_INIT) }, \
{ (uint16 *) &PORT_AWOPFC0 ,    (uint16)(PORT_AWOPFC0_INIT) }, \
{ (uint16 *) &PORT_AWOPIBC0 ,    (uint16)(PORT_AWOPIBC0_INIT) }, \
{ (uint16 *) &PORT_AWOPBDC0 ,    (uint16)(PORT_AWOPBDC0_INIT) }, \
{ (uint16 *) &PORT_AWOP0 ,    (uint16)(PORT_AWOP0_INIT) }, \
{ (uint16 *) &PORT_AWOPU0 ,    (uint16)(PORT_AWOPU0_INIT) }, \
{ (uint16 *) &PORT_AWOPD0 ,    (uint16)(PORT_AWOPD0_INIT) }, \
{ (uint16 *) &PORT_AWOPODC0 ,    (uint16)(PORT_AWOPODC0_INIT) }, \
{ (uint16 *) &PORT_AWOPDSC0 ,    (uint16)(PORT_AWOPDSC0_INIT) }, \
{ (uint16 *) &PORT_ISOPMC1 ,    (uint16)(PORT_ISOPMC1_INIT) }, \
{ (uint16 *) &PORT_ISOPM1 ,    (uint16)(PORT_ISOPM1_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC1 ,    (uint16)(PORT_ISOPIPC1_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE1 ,    (uint16)(PORT_ISOPFCE1_INIT) }, \
{ (uint16 *) &PORT_ISOPFC1 ,    (uint16)(PORT_ISOPFC1_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC1 ,    (uint16)(PORT_ISOPIBC1_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC1 ,    (uint16)(PORT_ISOPBDC1_INIT) }, \
{ (uint16 *) &PORT_ISOP1 ,    (uint16)(PORT_ISOP1_INIT) }, \
{ (uint16 *) &PORT_ISOPU1 ,    (uint16)(PORT_ISOPU1_INIT) }, \
{ (uint16 *) &PORT_ISOPD1 ,    (uint16)(PORT_ISOPD1_INIT) }, \
{ (uint16 *) &PORT_ISOPODC1 ,    (uint16)(PORT_ISOPODC1_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC1 ,    (uint16)(PORT_ISOPDSC1_INIT) }, \
{ (uint16 *) &PORT_ISOPMC3 ,    (uint16)(PORT_ISOPMC3_INIT) }, \
{ (uint16 *) &PORT_ISOPM3 ,    (uint16)(PORT_ISOPM3_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC3 ,    (uint16)(PORT_ISOPIPC3_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE3 ,    (uint16)(PORT_ISOPFCE3_INIT) }, \
{ (uint16 *) &PORT_ISOPFC3 ,    (uint16)(PORT_ISOPFC3_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC3 ,    (uint16)(PORT_ISOPIBC3_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC3 ,    (uint16)(PORT_ISOPBDC3_INIT) }, \
{ (uint16 *) &PORT_ISOP3 ,    (uint16)(PORT_ISOP3_INIT) }, \
{ (uint16 *) &PORT_ISOPU3 ,    (uint16)(PORT_ISOPU3_INIT) }, \
{ (uint16 *) &PORT_ISOPD3 ,    (uint16)(PORT_ISOPD3_INIT) }, \
{ (uint16 *) &PORT_ISOPODC3 ,    (uint16)(PORT_ISOPODC3_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC3 ,    (uint16)(PORT_ISOPDSC3_INIT) }, \
{ (uint16 *) &PORT_ISOPMC10 ,    (uint16)(PORT_ISOPMC10_INIT) }, \
{ (uint16 *) &PORT_ISOPM10 ,    (uint16)(PORT_ISOPM10_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC10 ,    (uint16)(PORT_ISOPIPC10_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE10 ,    (uint16)(PORT_ISOPFCE10_INIT) }, \
{ (uint16 *) &PORT_ISOPFC10 ,    (uint16)(PORT_ISOPFC10_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC10 ,    (uint16)(PORT_ISOPIBC10_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC10 ,    (uint16)(PORT_ISOPBDC10_INIT) }, \
{ (uint16 *) &PORT_ISOP10 ,    (uint16)(PORT_ISOP10_INIT) }, \
{ (uint16 *) &PORT_ISOPU10 ,    (uint16)(PORT_ISOPU10_INIT) }, \
{ (uint16 *) &PORT_ISOPD10 ,    (uint16)(PORT_ISOPD10_INIT) }, \
{ (uint16 *) &PORT_ISOPODC10 ,    (uint16)(PORT_ISOPODC10_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC10 ,    (uint16)(PORT_ISOPDSC10_INIT) }, \
{ (uint16 *) &PORT_ISOPMC11 ,    (uint16)(PORT_ISOPMC11_INIT) }, \
{ (uint16 *) &PORT_ISOPM11 ,    (uint16)(PORT_ISOPM11_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC11 ,    (uint16)(PORT_ISOPIPC11_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE11 ,    (uint16)(PORT_ISOPFCE11_INIT) }, \
{ (uint16 *) &PORT_ISOPFC11 ,    (uint16)(PORT_ISOPFC11_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC11 ,    (uint16)(PORT_ISOPIBC11_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC11 ,    (uint16)(PORT_ISOPBDC11_INIT) }, \
{ (uint16 *) &PORT_ISOP11 ,    (uint16)(PORT_ISOP11_INIT) }, \
{ (uint16 *) &PORT_ISOPU11 ,    (uint16)(PORT_ISOPU11_INIT) }, \
{ (uint16 *) &PORT_ISOPD11 ,    (uint16)(PORT_ISOPD11_INIT) }, \
{ (uint16 *) &PORT_ISOPODC11 ,    (uint16)(PORT_ISOPODC11_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC11 ,    (uint16)(PORT_ISOPDSC11_INIT) }, \
{ (uint16 *) &PORT_ISOPMC16 ,    (uint16)(PORT_ISOPMC16_INIT) }, \
{ (uint16 *) &PORT_ISOPM16 ,    (uint16)(PORT_ISOPM16_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC16 ,    (uint16)(PORT_ISOPIPC16_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE16 ,    (uint16)(PORT_ISOPFCE16_INIT) }, \
{ (uint16 *) &PORT_ISOPFC16 ,    (uint16)(PORT_ISOPFC16_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC16 ,    (uint16)(PORT_ISOPIBC16_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC16 ,    (uint16)(PORT_ISOPBDC16_INIT) }, \
{ (uint16 *) &PORT_ISOP16 ,    (uint16)(PORT_ISOP16_INIT) }, \
{ (uint16 *) &PORT_ISOPU16 ,    (uint16)(PORT_ISOPU16_INIT) }, \
{ (uint16 *) &PORT_ISOPD16 ,    (uint16)(PORT_ISOPD16_INIT) }, \
{ (uint16 *) &PORT_ISOPODC16 ,    (uint16)(PORT_ISOPODC16_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC16 ,    (uint16)(PORT_ISOPDSC16_INIT) }, \
{ (uint16 *) &PORT_ISOPMC17 ,    (uint16)(PORT_ISOPMC17_INIT) }, \
{ (uint16 *) &PORT_ISOPM17 ,    (uint16)(PORT_ISOPM17_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC17 ,    (uint16)(PORT_ISOPIPC17_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE17 ,    (uint16)(PORT_ISOPFCE17_INIT) }, \
{ (uint16 *) &PORT_ISOPFC17 ,    (uint16)(PORT_ISOPFC17_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC17 ,    (uint16)(PORT_ISOPIBC17_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC17 ,    (uint16)(PORT_ISOPBDC17_INIT) }, \
{ (uint16 *) &PORT_ISOP17 ,    (uint16)(PORT_ISOP17_INIT) }, \
{ (uint16 *) &PORT_ISOPU17 ,    (uint16)(PORT_ISOPU17_INIT) }, \
{ (uint16 *) &PORT_ISOPD17 ,    (uint16)(PORT_ISOPD17_INIT) }, \
{ (uint16 *) &PORT_ISOPODC17 ,    (uint16)(PORT_ISOPODC17_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC17 ,    (uint16)(PORT_ISOPDSC17_INIT) }, \
{ (uint16 *) &PORT_ISOPMC21 ,    (uint16)(PORT_ISOPMC21_INIT) }, \
{ (uint16 *) &PORT_ISOPM21 ,    (uint16)(PORT_ISOPM21_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC21 ,    (uint16)(PORT_ISOPIPC21_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE21 ,    (uint16)(PORT_ISOPFCE21_INIT) }, \
{ (uint16 *) &PORT_ISOPFC21 ,    (uint16)(PORT_ISOPFC21_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC21 ,    (uint16)(PORT_ISOPIBC21_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC21 ,    (uint16)(PORT_ISOPBDC21_INIT) }, \
{ (uint16 *) &PORT_ISOP21 ,    (uint16)(PORT_ISOP21_INIT) }, \
{ (uint16 *) &PORT_ISOPU21 ,    (uint16)(PORT_ISOPU21_INIT) }, \
{ (uint16 *) &PORT_ISOPD21 ,    (uint16)(PORT_ISOPD21_INIT) }, \
{ (uint16 *) &PORT_ISOPODC21 ,    (uint16)(PORT_ISOPODC21_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC21 ,    (uint16)(PORT_ISOPDSC21_INIT) }, \
{ (uint16 *) &PORT_ISOPMC42 ,    (uint16)(PORT_ISOPMC42_INIT) }, \
{ (uint16 *) &PORT_ISOPM42 ,    (uint16)(PORT_ISOPM42_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC42 ,    (uint16)(PORT_ISOPIPC42_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE42 ,    (uint16)(PORT_ISOPFCE42_INIT) }, \
{ (uint16 *) &PORT_ISOPFC42 ,    (uint16)(PORT_ISOPFC42_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC42 ,    (uint16)(PORT_ISOPIBC42_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC42 ,    (uint16)(PORT_ISOPBDC42_INIT) }, \
{ (uint16 *) &PORT_ISOP42 ,    (uint16)(PORT_ISOP42_INIT) }, \
{ (uint16 *) &PORT_ISOPU42 ,    (uint16)(PORT_ISOPU42_INIT) }, \
{ (uint16 *) &PORT_ISOPD42 ,    (uint16)(PORT_ISOPD42_INIT) }, \
{ (uint16 *) &PORT_ISOPODC42 ,    (uint16)(PORT_ISOPODC42_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC42 ,    (uint16)(PORT_ISOPDSC42_INIT) }, \
{ (uint16 *) &PORT_ISOPMC43 ,    (uint16)(PORT_ISOPMC43_INIT) }, \
{ (uint16 *) &PORT_ISOPM43 ,    (uint16)(PORT_ISOPM43_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC43 ,    (uint16)(PORT_ISOPIPC43_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE43 ,    (uint16)(PORT_ISOPFCE43_INIT) }, \
{ (uint16 *) &PORT_ISOPFC43 ,    (uint16)(PORT_ISOPFC43_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC43 ,    (uint16)(PORT_ISOPIBC43_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC43 ,    (uint16)(PORT_ISOPBDC43_INIT) }, \
{ (uint16 *) &PORT_ISOP43 ,    (uint16)(PORT_ISOP43_INIT) }, \
{ (uint16 *) &PORT_ISOPU43 ,    (uint16)(PORT_ISOPU43_INIT) }, \
{ (uint16 *) &PORT_ISOPD43 ,    (uint16)(PORT_ISOPD43_INIT) }, \
{ (uint16 *) &PORT_ISOPODC43 ,    (uint16)(PORT_ISOPODC43_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC43 ,    (uint16)(PORT_ISOPDSC43_INIT) }, \
{ (uint16 *) &PORT_ISOPMC44 ,    (uint16)(PORT_ISOPMC44_INIT) }, \
{ (uint16 *) &PORT_ISOPM44 ,    (uint16)(PORT_ISOPM44_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC44 ,    (uint16)(PORT_ISOPIPC44_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE44 ,    (uint16)(PORT_ISOPFCE44_INIT) }, \
{ (uint16 *) &PORT_ISOPFC44 ,    (uint16)(PORT_ISOPFC44_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC44 ,    (uint16)(PORT_ISOPIBC44_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC44 ,    (uint16)(PORT_ISOPBDC44_INIT) }, \
{ (uint16 *) &PORT_ISOP44 ,    (uint16)(PORT_ISOP44_INIT) }, \
{ (uint16 *) &PORT_ISOPU44 ,    (uint16)(PORT_ISOPU44_INIT) }, \
{ (uint16 *) &PORT_ISOPD44 ,    (uint16)(PORT_ISOPD44_INIT) }, \
{ (uint16 *) &PORT_ISOPODC44 ,    (uint16)(PORT_ISOPODC44_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC44 ,    (uint16)(PORT_ISOPDSC44_INIT) }, \
{ (uint16 *) &PORT_ISOPMC45 ,    (uint16)(PORT_ISOPMC45_INIT) }, \
{ (uint16 *) &PORT_ISOPM45 ,    (uint16)(PORT_ISOPM45_INIT) }, \
{ (uint16 *) &PORT_ISOPIPC45 ,    (uint16)(PORT_ISOPIPC45_INIT) }, \
{ (uint16 *) &PORT_ISOPFCE45 ,    (uint16)(PORT_ISOPFCE45_INIT) }, \
{ (uint16 *) &PORT_ISOPFC45 ,    (uint16)(PORT_ISOPFC45_INIT) }, \
{ (uint16 *) &PORT_ISOPIBC45 ,    (uint16)(PORT_ISOPIBC45_INIT) }, \
{ (uint16 *) &PORT_ISOPBDC45 ,    (uint16)(PORT_ISOPBDC45_INIT) }, \
{ (uint16 *) &PORT_ISOP45 ,    (uint16)(PORT_ISOP45_INIT) }, \
{ (uint16 *) &PORT_ISOPU45 ,    (uint16)(PORT_ISOPU45_INIT) }, \
{ (uint16 *) &PORT_ISOPD45 ,    (uint16)(PORT_ISOPD45_INIT) }, \
{ (uint16 *) &PORT_ISOPODC45 ,    (uint16)(PORT_ISOPODC45_INIT) }, \
{ (uint16 *) &PORT_ISOPDSC45 ,    (uint16)(PORT_ISOPDSC45_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPMC0 ,    (uint16)(PORTJ_AWOJPMC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPM0 ,    (uint16)(PORTJ_AWOJPM0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPIPC0 ,    (uint16)(PORTJ_AWOJPIPC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPFCE0 ,    (uint16)(PORTJ_AWOJPFCE0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPFC0 ,    (uint16)(PORTJ_AWOJPFC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPIBC0 ,    (uint16)(PORTJ_AWOJPIBC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPBDC0 ,    (uint16)(PORTJ_AWOJPBDC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJP0 ,    (uint16)(PORTJ_AWOJP0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPU0 ,    (uint16)(PORTJ_AWOJPU0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPD0 ,    (uint16)(PORTJ_AWOJPD0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPODC0 ,    (uint16)(PORTJ_AWOJPODC0_INIT) }, \
{ (uint16 *) &PORTJ_AWOJPDSC0 ,    (uint16)(PORTJ_AWOJPDSC0_INIT) }, \
/************************************************************************
**
** Description:     RH850 D1M1H Port Sleep Register List generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-29 19:58:12
************************************************************************/
#define      PORT_SLEEP_REG16_LIST \
{ (uint16 *) &PORT_AWOPMC0 ,    (uint16)(PORT_AWOPMC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPM0 ,    (uint16)(PORT_AWOPM0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPIPC0 ,    (uint16)(PORT_AWOPIPC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPFCE0 ,    (uint16)(PORT_AWOPFCE0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPFC0 ,    (uint16)(PORT_AWOPFC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPIBC0 ,    (uint16)(PORT_AWOPIBC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPBDC0 ,    (uint16)(PORT_AWOPBDC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOP0 ,    (uint16)(PORT_AWOP0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPU0 ,    (uint16)(PORT_AWOPU0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPD0 ,    (uint16)(PORT_AWOPD0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPODC0 ,    (uint16)(PORT_AWOPODC0_SLEEP) }, \
{ (uint16 *) &PORT_AWOPDSC0 ,    (uint16)(PORT_AWOPDSC0_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC1 ,    (uint16)(PORT_ISOPMC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM1 ,    (uint16)(PORT_ISOPM1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC1 ,    (uint16)(PORT_ISOPIPC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE1 ,    (uint16)(PORT_ISOPFCE1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC1 ,    (uint16)(PORT_ISOPFC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC1 ,    (uint16)(PORT_ISOPIBC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC1 ,    (uint16)(PORT_ISOPBDC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOP1 ,    (uint16)(PORT_ISOP1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU1 ,    (uint16)(PORT_ISOPU1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD1 ,    (uint16)(PORT_ISOPD1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC1 ,    (uint16)(PORT_ISOPODC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC1 ,    (uint16)(PORT_ISOPDSC1_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC3 ,    (uint16)(PORT_ISOPMC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM3 ,    (uint16)(PORT_ISOPM3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC3 ,    (uint16)(PORT_ISOPIPC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE3 ,    (uint16)(PORT_ISOPFCE3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC3 ,    (uint16)(PORT_ISOPFC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC3 ,    (uint16)(PORT_ISOPIBC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC3 ,    (uint16)(PORT_ISOPBDC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOP3 ,    (uint16)(PORT_ISOP3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU3 ,    (uint16)(PORT_ISOPU3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD3 ,    (uint16)(PORT_ISOPD3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC3 ,    (uint16)(PORT_ISOPODC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC3 ,    (uint16)(PORT_ISOPDSC3_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC10 ,    (uint16)(PORT_ISOPMC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM10 ,    (uint16)(PORT_ISOPM10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC10 ,    (uint16)(PORT_ISOPIPC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE10 ,    (uint16)(PORT_ISOPFCE10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC10 ,    (uint16)(PORT_ISOPFC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC10 ,    (uint16)(PORT_ISOPIBC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC10 ,    (uint16)(PORT_ISOPBDC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOP10 ,    (uint16)(PORT_ISOP10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU10 ,    (uint16)(PORT_ISOPU10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD10 ,    (uint16)(PORT_ISOPD10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC10 ,    (uint16)(PORT_ISOPODC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC10 ,    (uint16)(PORT_ISOPDSC10_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC11 ,    (uint16)(PORT_ISOPMC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM11 ,    (uint16)(PORT_ISOPM11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC11 ,    (uint16)(PORT_ISOPIPC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE11 ,    (uint16)(PORT_ISOPFCE11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC11 ,    (uint16)(PORT_ISOPFC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC11 ,    (uint16)(PORT_ISOPIBC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC11 ,    (uint16)(PORT_ISOPBDC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOP11 ,    (uint16)(PORT_ISOP11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU11 ,    (uint16)(PORT_ISOPU11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD11 ,    (uint16)(PORT_ISOPD11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC11 ,    (uint16)(PORT_ISOPODC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC11 ,    (uint16)(PORT_ISOPDSC11_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC16 ,    (uint16)(PORT_ISOPMC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM16 ,    (uint16)(PORT_ISOPM16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC16 ,    (uint16)(PORT_ISOPIPC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE16 ,    (uint16)(PORT_ISOPFCE16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC16 ,    (uint16)(PORT_ISOPFC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC16 ,    (uint16)(PORT_ISOPIBC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC16 ,    (uint16)(PORT_ISOPBDC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOP16 ,    (uint16)(PORT_ISOP16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU16 ,    (uint16)(PORT_ISOPU16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD16 ,    (uint16)(PORT_ISOPD16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC16 ,    (uint16)(PORT_ISOPODC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC16 ,    (uint16)(PORT_ISOPDSC16_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC17 ,    (uint16)(PORT_ISOPMC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM17 ,    (uint16)(PORT_ISOPM17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC17 ,    (uint16)(PORT_ISOPIPC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE17 ,    (uint16)(PORT_ISOPFCE17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC17 ,    (uint16)(PORT_ISOPFC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC17 ,    (uint16)(PORT_ISOPIBC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC17 ,    (uint16)(PORT_ISOPBDC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOP17 ,    (uint16)(PORT_ISOP17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU17 ,    (uint16)(PORT_ISOPU17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD17 ,    (uint16)(PORT_ISOPD17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC17 ,    (uint16)(PORT_ISOPODC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC17 ,    (uint16)(PORT_ISOPDSC17_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC21 ,    (uint16)(PORT_ISOPMC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM21 ,    (uint16)(PORT_ISOPM21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC21 ,    (uint16)(PORT_ISOPIPC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE21 ,    (uint16)(PORT_ISOPFCE21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC21 ,    (uint16)(PORT_ISOPFC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC21 ,    (uint16)(PORT_ISOPIBC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC21 ,    (uint16)(PORT_ISOPBDC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOP21 ,    (uint16)(PORT_ISOP21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU21 ,    (uint16)(PORT_ISOPU21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD21 ,    (uint16)(PORT_ISOPD21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC21 ,    (uint16)(PORT_ISOPODC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC21 ,    (uint16)(PORT_ISOPDSC21_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC42 ,    (uint16)(PORT_ISOPMC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM42 ,    (uint16)(PORT_ISOPM42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC42 ,    (uint16)(PORT_ISOPIPC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE42 ,    (uint16)(PORT_ISOPFCE42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC42 ,    (uint16)(PORT_ISOPFC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC42 ,    (uint16)(PORT_ISOPIBC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC42 ,    (uint16)(PORT_ISOPBDC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOP42 ,    (uint16)(PORT_ISOP42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU42 ,    (uint16)(PORT_ISOPU42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD42 ,    (uint16)(PORT_ISOPD42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC42 ,    (uint16)(PORT_ISOPODC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC42 ,    (uint16)(PORT_ISOPDSC42_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC43 ,    (uint16)(PORT_ISOPMC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM43 ,    (uint16)(PORT_ISOPM43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC43 ,    (uint16)(PORT_ISOPIPC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE43 ,    (uint16)(PORT_ISOPFCE43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC43 ,    (uint16)(PORT_ISOPFC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC43 ,    (uint16)(PORT_ISOPIBC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC43 ,    (uint16)(PORT_ISOPBDC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOP43 ,    (uint16)(PORT_ISOP43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU43 ,    (uint16)(PORT_ISOPU43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD43 ,    (uint16)(PORT_ISOPD43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC43 ,    (uint16)(PORT_ISOPODC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC43 ,    (uint16)(PORT_ISOPDSC43_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC44 ,    (uint16)(PORT_ISOPMC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM44 ,    (uint16)(PORT_ISOPM44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC44 ,    (uint16)(PORT_ISOPIPC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE44 ,    (uint16)(PORT_ISOPFCE44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC44 ,    (uint16)(PORT_ISOPFC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC44 ,    (uint16)(PORT_ISOPIBC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC44 ,    (uint16)(PORT_ISOPBDC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOP44 ,    (uint16)(PORT_ISOP44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU44 ,    (uint16)(PORT_ISOPU44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD44 ,    (uint16)(PORT_ISOPD44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC44 ,    (uint16)(PORT_ISOPODC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC44 ,    (uint16)(PORT_ISOPDSC44_SLEEP) }, \
{ (uint16 *) &PORT_ISOPMC45 ,    (uint16)(PORT_ISOPMC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPM45 ,    (uint16)(PORT_ISOPM45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIPC45 ,    (uint16)(PORT_ISOPIPC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFCE45 ,    (uint16)(PORT_ISOPFCE45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPFC45 ,    (uint16)(PORT_ISOPFC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPIBC45 ,    (uint16)(PORT_ISOPIBC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPBDC45 ,    (uint16)(PORT_ISOPBDC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOP45 ,    (uint16)(PORT_ISOP45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPU45 ,    (uint16)(PORT_ISOPU45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPD45 ,    (uint16)(PORT_ISOPD45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPODC45 ,    (uint16)(PORT_ISOPODC45_SLEEP) }, \
{ (uint16 *) &PORT_ISOPDSC45 ,    (uint16)(PORT_ISOPDSC45_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPMC0 ,    (uint16)(PORTJ_AWOJPMC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPM0 ,    (uint16)(PORTJ_AWOJPM0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPIPC0 ,    (uint16)(PORTJ_AWOJPIPC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPFCE0 ,    (uint16)(PORTJ_AWOJPFCE0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPFC0 ,    (uint16)(PORTJ_AWOJPFC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPIBC0 ,    (uint16)(PORTJ_AWOJPIBC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPBDC0 ,    (uint16)(PORTJ_AWOJPBDC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJP0 ,    (uint16)(PORTJ_AWOJP0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPU0 ,    (uint16)(PORTJ_AWOJPU0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPD0 ,    (uint16)(PORTJ_AWOJPD0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPODC0 ,    (uint16)(PORTJ_AWOJPODC0_SLEEP) }, \
{ (uint16 *) &PORTJ_AWOJPDSC0 ,    (uint16)(PORTJ_AWOJPDSC0_SLEEP) }, \
/***************************************************************************
**
** Description:     RH850 D1M1H Port Pin Register Map List generated by tool
**                  automatically  Don't modify it manually.
** Author:          niujianlong
** Generated Date:  2016-07-29 19:58:12
***************************************************************************/
#define      PORT_PIN_REG16_LIST     \
{ PORT0_0, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_0)   }, \
{ PORT0_1, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_1)   }, \
{ PORT0_2, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_2)   }, \
{ PORT0_3, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_3)   }, \
{ PORT0_4, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_4)   }, \
{ PORT0_5, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_5)   }, \
{ PORT0_6, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_6)   }, \
{ PORT0_7, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_7)   }, \
{ PORT0_8, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_8)   }, \
{ PORT0_9, (uint16 *) &PORT_AWOPMC0 , (uint16 *) &PORT_AWOPM0, (uint16 *) &PORT_AWOPFC0, (uint16 *) &PORT_AWOPFCE0, (uint16 *) &PORT_AWOPIBC0,  (uint16)(BIT_9)   }, \
\
{ PORT1_0, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1, (uint16 *) &PORT_ISOPIBC1,  (uint16)(BIT_0)   }, \
{ PORT1_1, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1, (uint16 *) &PORT_ISOPIBC1,  (uint16)(BIT_1)   }, \
{ PORT1_2, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1, (uint16 *) &PORT_ISOPIBC1,  (uint16)(BIT_2)   }, \
{ PORT1_3, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1, (uint16 *) &PORT_ISOPIBC1,  (uint16)(BIT_3)   }, \
{ PORT1_4, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1, (uint16 *) &PORT_ISOPIBC1,  (uint16)(BIT_4)   }, \
{ PORT1_5, (uint16 *) &PORT_ISOPMC1 , (uint16 *) &PORT_ISOPM1, (uint16 *) &PORT_ISOPFC1, (uint16 *) &PORT_ISOPFCE1, (uint16 *) &PORT_ISOPIBC1,  (uint16)(BIT_5)   }, \
\
{ PORT3_0, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_0)   }, \
{ PORT3_1, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_1)   }, \
{ PORT3_2, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_2)   }, \
{ PORT3_3, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_3)   }, \
{ PORT3_4, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_4)   }, \
{ PORT3_5, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_5)   }, \
{ PORT3_6, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_6)   }, \
{ PORT3_7, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_7)   }, \
{ PORT3_8, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_8)   }, \
{ PORT3_9, (uint16 *) &PORT_ISOPMC3 , (uint16 *) &PORT_ISOPM3, (uint16 *) &PORT_ISOPFC3, (uint16 *) &PORT_ISOPFCE3, (uint16 *) &PORT_ISOPIBC3,  (uint16)(BIT_9)   }, \
\
{ PORT10_0, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_0)   }, \
{ PORT10_1, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_1)   }, \
{ PORT10_2, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_2)   }, \
{ PORT10_3, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_3)   }, \
{ PORT10_4, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_4)   }, \
{ PORT10_5, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_5)   }, \
{ PORT10_6, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_6)   }, \
{ PORT10_7, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_7)   }, \
{ PORT10_8, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_8)   }, \
{ PORT10_9, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_9)   }, \
{ PORT10_10, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_10)   }, \
{ PORT10_11, (uint16 *) &PORT_ISOPMC10 , (uint16 *) &PORT_ISOPM10, (uint16 *) &PORT_ISOPFC10, (uint16 *) &PORT_ISOPFCE10, (uint16 *) &PORT_ISOPIBC10,  (uint16)(BIT_11)   }, \
\
{ PORT11_0, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) NULL, (uint16 *) &PORT_ISOPIBC11,  (uint16)(BIT_0)   }, \
{ PORT11_1, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) NULL, (uint16 *) &PORT_ISOPIBC11,  (uint16)(BIT_1)   }, \
{ PORT11_2, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) NULL, (uint16 *) &PORT_ISOPIBC11,  (uint16)(BIT_2)   }, \
{ PORT11_3, (uint16 *) &PORT_ISOPMC11 , (uint16 *) &PORT_ISOPM11, (uint16 *) &PORT_ISOPFC11, (uint16 *) NULL, (uint16 *) &PORT_ISOPIBC11,  (uint16)(BIT_3)   }, \
\
{ PORT16_0, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_0)   }, \
{ PORT16_1, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_1)   }, \
{ PORT16_2, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_2)   }, \
{ PORT16_3, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_3)   }, \
{ PORT16_4, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_4)   }, \
{ PORT16_5, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_5)   }, \
{ PORT16_6, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_6)   }, \
{ PORT16_7, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_7)   }, \
{ PORT16_8, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_8)   }, \
{ PORT16_9, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_9)   }, \
{ PORT16_10, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_10)   }, \
{ PORT16_11, (uint16 *) &PORT_ISOPMC16 , (uint16 *) &PORT_ISOPM16, (uint16 *) &PORT_ISOPFC16, (uint16 *) &PORT_ISOPFCE16, (uint16 *) &PORT_ISOPIBC16,  (uint16)(BIT_11)   }, \
\
{ PORT17_0, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_0)   }, \
{ PORT17_1, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_1)   }, \
{ PORT17_2, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_2)   }, \
{ PORT17_3, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_3)   }, \
{ PORT17_4, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_4)   }, \
{ PORT17_5, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_5)   }, \
{ PORT17_6, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_6)   }, \
{ PORT17_7, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_7)   }, \
{ PORT17_8, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_8)   }, \
{ PORT17_9, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_9)   }, \
{ PORT17_10, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_10)   }, \
{ PORT17_11, (uint16 *) &PORT_ISOPMC17 , (uint16 *) &PORT_ISOPM17, (uint16 *) &PORT_ISOPFC17, (uint16 *) &PORT_ISOPFCE17, (uint16 *) &PORT_ISOPIBC17,  (uint16)(BIT_11)   }, \
\
{ PORT21_0, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_0)   }, \
{ PORT21_1, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_1)   }, \
{ PORT21_2, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_2)   }, \
{ PORT21_3, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_3)   }, \
{ PORT21_4, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_4)   }, \
{ PORT21_5, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_5)   }, \
{ PORT21_6, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_6)   }, \
{ PORT21_7, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_7)   }, \
{ PORT21_8, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_8)   }, \
{ PORT21_9, (uint16 *) &PORT_ISOPMC21 , (uint16 *) &PORT_ISOPM21, (uint16 *) &PORT_ISOPFC21, (uint16 *) &PORT_ISOPFCE21, (uint16 *) &PORT_ISOPIBC21,  (uint16)(BIT_9)   }, \
\
{ PORT42_0, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_0)   }, \
{ PORT42_1, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_1)   }, \
{ PORT42_2, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_2)   }, \
{ PORT42_3, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_3)   }, \
{ PORT42_4, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_4)   }, \
{ PORT42_5, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_5)   }, \
{ PORT42_6, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_6)   }, \
{ PORT42_7, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_7)   }, \
{ PORT42_8, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_8)   }, \
{ PORT42_9, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_9)   }, \
{ PORT42_10, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_10)   }, \
{ PORT42_11, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_11)   }, \
{ PORT42_12, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_12)   }, \
{ PORT42_13, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_13)   }, \
{ PORT42_14, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_14)   }, \
{ PORT42_15, (uint16 *) &PORT_ISOPMC42 , (uint16 *) &PORT_ISOPM42, (uint16 *) &PORT_ISOPFC42, (uint16 *) &PORT_ISOPFCE42, (uint16 *) &PORT_ISOPIBC42,  (uint16)(BIT_15)   }, \
\
{ PORT43_0, (uint16 *) &PORT_ISOPMC43 , (uint16 *) &PORT_ISOPM43, (uint16 *) &PORT_ISOPFC43, (uint16 *) NULL, (uint16 *) &PORT_ISOPIBC43,  (uint16)(BIT_0)   }, \
{ PORT43_1, (uint16 *) &PORT_ISOPMC43 , (uint16 *) &PORT_ISOPM43, (uint16 *) &PORT_ISOPFC43, (uint16 *) NULL, (uint16 *) &PORT_ISOPIBC43,  (uint16)(BIT_1)   }, \
\
{ PORT44_0, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_0)   }, \
{ PORT44_1, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_1)   }, \
{ PORT44_2, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_2)   }, \
{ PORT44_3, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_3)   }, \
{ PORT44_4, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_4)   }, \
{ PORT44_5, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_5)   }, \
{ PORT44_6, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_6)   }, \
{ PORT44_7, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_7)   }, \
{ PORT44_8, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_8)   }, \
{ PORT44_9, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_9)   }, \
{ PORT44_10, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_10)   }, \
{ PORT44_11, (uint16 *) &PORT_ISOPMC44 , (uint16 *) &PORT_ISOPM44, (uint16 *) &PORT_ISOPFC44, (uint16 *) &PORT_ISOPFCE44, (uint16 *) &PORT_ISOPIBC44,  (uint16)(BIT_11)   }, \
\
{ PORT45_0, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_0)   }, \
{ PORT45_1, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_1)   }, \
{ PORT45_2, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_2)   }, \
{ PORT45_3, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_3)   }, \
{ PORT45_4, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_4)   }, \
{ PORT45_5, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_5)   }, \
{ PORT45_6, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_6)   }, \
{ PORT45_7, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_7)   }, \
{ PORT45_8, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_8)   }, \
{ PORT45_9, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_9)   }, \
{ PORT45_10, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_10)   }, \
{ PORT45_11, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_11)   }, \
{ PORT45_12, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_12)   }, \
{ PORT45_13, (uint16 *) &PORT_ISOPMC45 , (uint16 *) &PORT_ISOPM45, (uint16 *) &PORT_ISOPFC45, (uint16 *) &PORT_ISOPFCE45, (uint16 *) &PORT_ISOPIBC45,  (uint16)(BIT_13)   }, \
\
{ JPORT0_0, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0, (uint16 *) &PORTJ_AWOJPIBC0,  (uint16)(BIT_0)   }, \
{ JPORT0_1, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0, (uint16 *) &PORTJ_AWOJPIBC0,  (uint16)(BIT_1)   }, \
{ JPORT0_2, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0, (uint16 *) &PORTJ_AWOJPIBC0,  (uint16)(BIT_2)   }, \
{ JPORT0_3, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0, (uint16 *) &PORTJ_AWOJPIBC0,  (uint16)(BIT_3)   }, \
{ JPORT0_4, (uint16 *) &PORTJ_AWOJPMC0 , (uint16 *) &PORTJ_AWOJPM0, (uint16 *) &PORTJ_AWOJPFC0, (uint16 *) &PORTJ_AWOJPFCE0, (uint16 *) &PORTJ_AWOJPIBC0,  (uint16)(BIT_4)   }, \


#endif

/**************************************End Of File******************************************/
