/*****************************************************************************
**  Project       BAIC C11 Cluster Project
**  (c) copyright 2016
**  Company       O-film
**                All rights reserved
**  Secrecy Level STRICTLY CONFIDENTIAL
*******************************************************************************
**
**          File  : CANMissingProcess.h
**          Author: niujianlong
**
**          Date  : 2016-08-12 15:06:52
**          Description: modified by the open software
**          Warning :This file generated by tool don't modify it manually.
**          version: V_0_1
**
******************************************************************************/

#ifndef CANMISSINGPROCESS_H
#define CANMISSINGPROCESS_H


#include "CANProcess.h"
#include "CANService.h"
#include "can_bus_off.h"

#ifdef   CANMISSINGPROCESS_C 
#define  EXTERN
#else
#define  EXTERN    extern
#endif
/*************************************************************************
**              Set Missing Default Value                               **
**************************************************************************/
EXTERN void Setvcu_0x212MissingDefaultValue(void);
EXTERN void Setvcu_0x214MissingDefaultValue(void);
EXTERN void Setmcu_0x230MissingDefaultValue(void);
EXTERN void Setabs_0x318MissingDefaultValue(void);
EXTERN void Setmcu_0x430MissingDefaultValue(void);
EXTERN void Setbms_0x450MissingDefaultValue(void);
EXTERN void Setbms_0x451MissingDefaultValue(void);
EXTERN void Seteps_0x470MissingDefaultValue(void);
EXTERN void Setepb_0x4c8MissingDefaultValue(void);
EXTERN void Setecc_0x4e0MissingDefaultValue(void);
EXTERN void Setehu_0x585MissingDefaultValue(void);
EXTERN void Setvcu_0x611MissingDefaultValue(void);
EXTERN void Setvcu_0x615MissingDefaultValue(void);
EXTERN void Setvcu_0x616MissingDefaultValue(void);
EXTERN void Setvcu_0x617MissingDefaultValue(void);
EXTERN void Setvcu_0x61dMissingDefaultValue(void);
EXTERN void Setpdc_0x1b0MissingDefaultValue(void);
EXTERN void Setvbus_vcu_0x214MissingDefaultValue(void);
EXTERN void Setvbus_mcu_0x230MissingDefaultValue(void);
EXTERN void Settpms_0x2a0MissingDefaultValue(void);
EXTERN void Setpeps_0x479MissingDefaultValue(void);
EXTERN void Setbcm_0x4a0MissingDefaultValue(void);
EXTERN void Setuec_0x4c9MissingDefaultValue(void);
EXTERN void Setpeps_0x570MissingDefaultValue(void);
EXTERN void Seticm_0x620MissingDefaultValue(void);
EXTERN void Setbcm_0x660MissingDefaultValue(void);
EXTERN void Setbcm_0x661MissingDefaultValue(void);
EXTERN void Seticm_0x6a0MissingDefaultValue(void);
EXTERN void Seticm_0x6a2MissingDefaultValue(void);
EXTERN void Seticm_0x6afMissingDefaultValue(void);
EXTERN void Settbox_0x6f2MissingDefaultValue(void);


#undef EXTERN
#endif