/*0x620  ICM_0x620*/
EXTERN void set_ICM_DATA_VALID_ODO( uint8 ICM_620_DATA_VALID_ODO);
EXTERN void set_ICM_ODOMETER_RESET_COUNTER( uint8 ICM_620_ODOMETER_RESET_COUNTER);
EXTERN void set_ICM_DISPLAYED_TOTAL_DISTANCE( uint32 ICM_620_DISPLAYED_TOTAL_DISTANCE);
EXTERN void set_ICM_ODOMETER_OFFSET( uint8 ICM_620_ODOMETER_OFFSET);
/*0x6a0  ICM_0x6A0*/
EXTERN void set_ICM_ODO( uint32 ICM_6A0_ODO);
/*0x6a2  ICM_0x6A2*/
EXTERN void set_ICM_IP_Fault( uint8 ICM_6A2_IP_Fault);
EXTERN void set_ICM_IP_Theme( uint8 ICM_6A2_IP_Theme);
EXTERN void set_ICM_Distance_To_Service( uint32 ICM_6A2_Distance_To_Service);
EXTERN void set_ICM_Day_To_Service( uint16 ICM_6A2_Day_To_Service);
/*0x6af  ICM_0x6AF*/
EXTERN void set_ICM_CAL_VERS( uint8 ICM_6AF_CAL_VERS);
EXTERN void set_ICM_PART_VERS( uint32 ICM_6AF_PART_VERS);
EXTERN void set_ICM_HW_VERS( uint8 ICM_6AF_HW_VERS);
EXTERN void set_ICM_SW_VERS( uint8 ICM_6AF_SW_VERS);
